### ISSUE TITLE
PS3 fbneo samples sound rushing

### ISSUE THREAD

**Issue by angomania** [finalburnneo/FBNeo#191] opened 2019-12-11 15:51 UTC
I´m using Retroarch and the fbneo core. All fbneo games working fine.

But games who need samples like zaxxon or dkong have only a loud sound rushing. 
The samples are in the right folder (system/fbneo/samples/*.zip). 
I´m using the same samples from my PC retroarch and fbneo core. There are no problems with the samples.

**Comment by barbudreadmon** [comment] 2019-12-11 16:44
Since this is on PS3, it's probably some kind of big endian issue. Maybe @dinkc64 can help with this, however he is quite busy atm so don't expect a fix anytime soon.

**Comment by dinkc64** [comment] 2019-12-12 01:58
angomania, I'll try to figure out what is wrong and post back here.

barbudreadmon,
IMO pivotal classic games like that need to be working right, though.  for everyone:)

**Comment by dinkc64** [comment] 2019-12-12 03:36
@angomania,
I just checked in a test-fix for the sample soundcore on big endian systems, please give it a try (when the update is available) and please let me know if it fixes the problem.  Sometimes these things can be difficult and take 1-3 tries :)
Thanks for your bug report - they're always appreciated!

best regards,
-dink

**Comment by angomania** [comment] 2019-12-12 06:44
Thank you very much @dinkc64 :)
I will give the next update a try and report back.

**Comment by barbudreadmon** [comment] 2019-12-12 08:53
> I will give the next update a try and report back.

The new version should be available right now.

**Comment by angomania** [comment] 2019-12-12 11:16
> > I will give the next update a try and report back.
> 
> The new version should be available right now.

Yes, I saw the changes. Unfortunately I have no programing skills. 
So I have to wait for a new PS3 core on [xbins.org](https://xbins.org/libretro/nightly/playstation/ps3/latest/)  bevore I can test it

**Comment by barbudreadmon** [comment] 2019-12-12 12:23
> a new PS3 core on xbins.org

Yeah, as i said it should already be available

**Comment by angomania** [comment] 2019-12-13 05:41
I´ve Tested the updated core. Problem still exists.

**Comment by dinkc64** [comment] 2019-12-13 14:14
Thanks for testing, endian issues are usually quite insidious and hard to get right on the first time.

 I'll have another go at it today and let you know!

best regards,
- dink

**Comment by grant2258** [comment] 2019-12-15 00:10
@dinkc64 just a quick question does your rom/sampling loading routines take machine endian into account when loading roms. If so it could be that msb or lsb flag isint being defined correctly in the makefile. As im not familiar with your code base.

Just to show you what i mean from the mame source of 2003 here is what im talking about.

#ifdef MSB_FIRST
#define mame_fread_msbfirst mame_fread
#define mame_fwrite_msbfirst mame_fwrite
#define mame_fread_lsbfirst mame_fread_swap
#define mame_fwrite_lsbfirst mame_fwrite_swap
#else


#define mame_fread_msbfirst mame_fread_swap
#define mame_fwrite_msbfirst mame_fwrite_swap
#define mame_fread_lsbfirst mame_fread
#define mame_fwrite_lsbfirst mame_fwrite
#endif

**Comment by dinkc64** [comment] 2019-12-15 04:21
angomania, can you try updating the core again?  I can't locate any other endian issues in the sample playback core.  I just wonder if the fix and the core on the xbins site crossed paths or something.  
also can you get me the logfile (if possible?)?  This might help me locate the problem.

best regards,
- dink

**Comment by angomania** [comment] 2019-12-15 08:00
Ok, tested again. Same error. 
However, I noticed that the last core is the same as the one before. I think I have to wait until the new core is online. I'll try again later.

I´ve uploaded the logfile [here](https://pastebin.com/Whr0KCh6).

Btw I´ve tested the game and sample with core mame_2003 without problems. The samples were loaded successfully. [For a better understanding I´ve made a little video of the problem](https://streamable.com/znr7h).

**Comment by barbudreadmon** [comment] 2019-12-15 09:04
@angomania there was no new fix, dink only wanted to double check that you were using the latest version.
Can you do some kind of recording ? Maybe seeing what happens exactly will help figuring out the issue.

@grant2258 i confirm ps3 is built as a big endian target in fbneo

**Comment by dinkc64** [comment] 2019-12-15 14:59
angomania, thank you for the log and video, I will certainly give it another go tonight :)

best regards,
- dink

**Comment by grant2258** [comment] 2019-12-17 17:49
One thing I did notice in your logs is your sample names are showing up with odd characters in the debug lines 41 - 52

**Comment by dinkc64** [comment] 2019-12-18 00:38
grant, that's alright - the bad names are due to a clash between dbcs (unicode) vs. regular 8bit characters.

**Comment by grant2258** [comment] 2019-12-19 15:43
apparently fbneo will run in the ps3 emulator for testing. I guess you would need an official sdk to build it though if you wanted to make changes.

**Comment by dinkc64** [comment] 2019-12-19 15:55
I didn't have time to check into this further, but will hopefully soon!

**Comment by grant2258** [comment] 2019-12-19 16:28
@barbudreadmon sorry i wasnt real clear on this.What i mean is the code here.

https://github.com/finalburnneo/FBNeo/blob/bddf08ddc30af4ddcc0084c84ac6e7b498c07ee7/src/burn/burnint.h#L19-L34

that was what i was referring too

**Comment by barbudreadmon** [comment] 2019-12-19 19:33
@grant2258 the code is defered to `burn_endian.h`, which is a port specific file, in the case of the libretro port it is located at https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/burn_endian.h

I can't guarantee the `BURN_ENDIAN_SWAP_*` macros are right for ps3, but i think it was originally written by @CaptainCPS, an old fbalpha contributor and owner of ps3, he probably tested those. The only thing i can confirm is that the nintendo ones, which are really similar, are ok (a bunch of big endian issues were solved for wii/siiu owners in the past).

**Comment by dinkc64** [comment] 2019-12-20 13:43
@angomania,
I just committed another test-fix for this problem, please give it a try when you can :)
best regards,
- dink

**Comment by angomania** [comment] 2019-12-23 13:55
@dinkc64
... as soon as there is an update on xbin :)

**Comment by barbudreadmon** [comment] 2019-12-23 14:29
> as soon as there is an update on xbin

The update has been there for 2 days already.

**Comment by angomania** [comment] 2019-12-23 16:25
...hmm, I´m looking since 2 days on xbin but there is no update. I´ve compared the "fbneo_libretro_ps3.SELF" from  the installed version with the one from xbin, but they are the same.

**Comment by barbudreadmon** [comment] 2019-12-23 16:43
Actually it's more like 3 days. I don't understand the part where you say you "compared". Can you just update/reinstall/whatever & check that the new version is bf6c36b88d1340ffbe6c5ee0c9e4ac1b6cd09782 as expected ?

**Comment by angomania** [comment] 2019-12-23 18:54
I compared the installed core (more like 8 days old) with the new one from [Xbin ](https://xbins.org/libretro/nightly/playstation/ps3/latest/cex-ps3/fbneo_libretro_ps3.SELF.zip) with TotalCommander (File compare) and I don't see any difference. 
Only the the time stamp from Xbin is different.

I am sorry if I am not understood correctly. My English is not very good.

**Comment by dinkc64** [comment] 2019-12-24 00:44
angomania, maybe xbins fbneo core not up-to-date? :(

**Comment by barbudreadmon** [comment] 2019-12-24 07:40
@angomania force a reinstall, then tell me the exact version it is (bottom left corner of RA menu)

**Comment by angomania** [comment] 2019-12-25 17:58
@barbudreadmon  Ok, I tested a lot today. 

Did a clean install on my PS3 with the officially package from [retroarch](https://xbins.org/libretro/stable/1.8.1/playstation/ps3/RetroArch.PS3.CEX.PS3.pkg) and I found other abnormalities with the FBNeo core.
- If I load the fbneo core, I think the main menu is messed up. In the manin menu there are a lot of "Load Core *****" entrys. Also the entry "Core Updater" is missing. This only happens with the fbneo core core! ([Screenshot](https://ibb.co/KyKK5Mw)) ... btw, this problem also exists on my PC Retroarch.
- There is also no fbneo core entry in the "Core Updater" menu ([Screenshot](https://ibb.co/5YYxYYf)). You have to update the core manually over ftp.

I´ve updated the core manually, latest version is v0.2.97.44 d454549 , the problem with external Wav files still exists.

**Comment by barbudreadmon** [comment] 2019-12-25 19:30
> latest version is v0.2.97.44 d454549

This version is from mid november, which means @dinkc64 's first attempt at fixing this is not even included. We'll have to revert second attempt at fixing this, and find out why the core isn't rebuilt.

> In the manin menu there are a lot of "Load Core *****" entrys.

That's normal, fbneo uses RA's subsystems to emulate various consoles & computers.

> Also the entry "Core Updater" is missing

It's below the "Load Core *****" entries for me

**Comment by dinkc64** [comment] 2019-12-25 22:13
barbudreadmon is right, I'll revert the second fix - I'm quite confident that the first fix will do the trick.  now does anyone know why the ps3 core isn't being built? :)

**Comment by barbudreadmon** [comment] 2019-12-26 12:43
@angomania I'm trying to get to the bottom of this, however it seems those ps3 builds aren't managed by the libretro team, so it might take some time before i get in touch with the people managing this buildbot. I'll let you know when i learn something.

**Comment by angomania** [comment] 2019-12-27 07:17
> > Also the entry "Core Updater" is missing
> 
> It's below the "Load Core *****" entries for me

I checked again.
On the PC it´s below "Load Core *****", but the entry is missing on the PS3.

**Comment by angomania** [comment] 2019-12-27 07:51
> > latest version is v0.2.97.44 [d454549](https://github.com/finalburnneo/FBNeo/commit/d4545491ff09b5ea5d681ab140c4df603c892e4e)
> 
> This version is from mid november, which means @dinkc64 's first attempt at fixing this is not even included. We'll have to revert second attempt at fixing this, and find out why the core isn't rebuilt.
> 
> > In the manin menu there are a lot of "Load Core *****" entrys.
> 
> That's normal, fbneo uses RA's subsystems to emulate various consoles & computers.
> 
> > Also the entry "Core Updater" is missing
> 
> It's below the "Load Core *****" entries for me

**Comment by angomania** [comment] 2019-12-30 15:48
... accidentally closed, sorry

**Comment by angomania** [comment] 2020-01-02 13:42
I read in the forum that there are problems with the new PS3 retroarch 1.8.2 version:
["Something seems to have happened with the people that usually provide those builds. We haven’t spoken to them about it yet, but unless/until they get something going for it, users will need to compile it themselves."](https://forums.libretro.com/t/retroarch-1-8-2-released/25588/2)

I don't have programming skills ... could someone build the latest PS3 fbneo core for testing, please?

**Comment by barbudreadmon** [comment] 2020-01-02 14:07
> could someone build the latest PS3 fbneo core for testing, please?

Not gonna happen, sorry, i don't own the software, i don't even know how to legally acquire it, and afaik it's really pricy (several thousands of dollars), which is why the libretro team doesn't provide those binaries.

**Comment by dinkc64** [comment] 2020-01-02 14:31
I work on the windows version, and have no idea how to compile it for PS3, sorry about that!

**Comment by angomania** [comment] 2020-01-13 19:00
@barbudreadmon   good news :) 
I´ve visited at Xbins and was surprised there was a PS3 updates. Retroarch 1.8.2 and the nightlys are up to date. I´ve tested the FBNeo Core v0.2.97.44 6514055 and voila, samples are working fine.

The only thing I had to change in the core options, was to set the sample rate from 4800 to 4100, otherwise the samples sound distorted.

**Comment by barbudreadmon** [comment] 2020-01-13 19:22
> was to set the sample rate from 48000 to 44100

Yes, i heard the samples must match the samplerate, i think pack for different samplerates can be found on the web, the ones you are using are probably for 44100.

Anyway, thanks for the heads-up, i'll close !

**Comment by dinkc64** [comment] 2020-01-14 04:26
Hey this is great news :)
@angomania can you please make a video/recording of how the samples sound when set the rate to 48000 ?  our sampledriver should automatically upscale or downscale to the correct rate, and the distortion makes me think something might be wrong here still.

thanks and best regards,
- dink

**Comment by angomania** [comment] 2020-01-14 07:14
@dinkc64 here is a [sample](https://voca.ro/2t3KLskQwWp). 
I took it with my handy about 3 meters away from the tv.
The first one is sample rate 44100 the second one is sample rate 48000.

**Comment by barbudreadmon** [comment] 2020-01-14 07:55
> our samplecore should automatically upscale or downscale to the correct rate

Indeed it does, i can't remember where i heard about the matching samplerate stuff, it might have been about MAME actually.

**Comment by dinkc64** [comment] 2020-01-14 14:44
angomania, thanks - what game is that fram? :)

**Comment by barbudreadmon** [comment] 2020-08-05 11:36
@dinkc64 Well, actually it doesn't seem fixed to me, using same samples on x86_64 & ps3, zaxxon seemed ok at 44100, applying the clipping fix from neocd (i.e storing to a short before clipping) even seemed to help with the conversion.
However, in the case of dkong, whatever samplerate i used (my samples for this one are 11025hz btw), the result was totally different from x86_64, i have distorted/missing sound and "blank" sound isn't that blank

**Comment by barbudreadmon** [comment] 2020-08-06 09:51
It turns out i had the wrong idea about dkong, there might be a problem indeed with samples, which i think is fixed by replacing the cast by `(INT16)` at https://github.com/finalburnneo/FBNeo/blob/66108ebeccb191f2c02a32bab4a15eb2bbf7e171/src/burn/snd/samples.cpp#L151-L152

But there is also a separate issue with dac !

**Comment by barbudreadmon** [comment] 2020-08-06 16:34
dkong and zaxxon now sound perfect on big-endian, closing !

**Closed by barbudreadmon** 2020-08-06 16:34 UTC
Labels: bug, emulation, platform specific

**Comment by dinkc64** [comment] 2020-08-06 23:31
woohoo, finally! :)
