### ISSUE TITLE
Help! Trackball gameplay moves very slow! Please patch or update this on FBNeo!!

### ISSUE THREAD

**Issue by WillRussellFoley** [finalburnneo/FBNeo#1905] opened 2024-11-06 21:14 UTC
When using the trackball for games like centipede and bowling, the characters/game action don't move as fast and accurate as they used to.

I recently cleaned out my x arcade  trackball thinking it might be full of dust and dirt inside but that wasn't the problem.

I also tried adjusting the "mouse speed" on the Retroarch menu but nothing changes.

I really don't know much technical details about mouse or analog speed or controls so maybe updating FBNeo would be the best way to fix this lolhttps://github.com/user-attachments/assets/939aa529-2ea3-4086-b9c8-c416286b4a23

**Comment by barbudreadmon** [comment] 2024-11-06 21:24
Duplicate of https://github.com/finalburnneo/FBNeo/issues/1880
This is a retroarch bug.
As previously said, the only workaround is to increase "analog speed" in core options.

**Closed** 2024-11-06 21:27 UTC

**Comment by barbudreadmon** [comment] 2024-11-07 11:45
I just noticed runahead is causing additional slowness, so you might want to make sure it's not enabled.

**Comment by WillRussellFoley** [comment] 2024-11-07 19:51
@barbudreadmon 
Is there a source on how to disable that and also one on how to adjust the analog speed?

I'm not that savvy and can't seem to find anything.

**Comment by WillRussellFoley** [comment] 2024-11-08 01:31
@barbudreadmon 
Is this the analog setting you are referring to? If so, it's not working. The trackball I am using runs on a computer mouse interface.

But if that's not it I can't find any thing on the core settings that says "analog speed"

**Comment by barbudreadmon** [comment] 2024-11-08 08:36
>Is this the analog setting you are referring to?

No, that's retroarch general settings.

>I can't find any thing on the core settings that says "analog speed"

Look at your bottom left corner, you don't have any core running, so there is no way anything having to do with the running core would ever appear.

![centiped1](https://github.com/user-attachments/assets/841300e0-938f-400b-bfda-ef99251b9ef3)
![centiped2](https://github.com/user-attachments/assets/8bf6c37d-9556-43b3-b12b-47ef27932f88)

Note that your version of retroarch is several years old, i *think* core options might have been accessed through `Quick Menu > Options` instead of `Quick Menu > Core Options` back then.

Runahead settings are accessed through `Quick Menu > Latency`

**Comment by WillRussellFoley** [comment] 2024-11-09 00:34
@barbudreadmon 
That worked! Thank you very much. And thank you for that extra detail. Mine version of Retroarch is outdated for sure.
