### ISSUE TITLE
Trackball gameplay/feedback running very slow. Might be an FBNeo on RetroPie problem?

### ISSUE THREAD

**Issue by WillRussellFoley** [finalburnneo/FBNeo#1880] opened 2024-09-19 19:54 UTC
The reason why I’m writing this on here is because I already cleaned out the trackball But when rolling the trackball for games like centipede, missile command and capcom bowling, the game characters move very slow even though I’m spinning the trackball like crazy almost.

I recently have been doing a lot of tweaking and updated to FBNeo to get some other games to work which I guess could have caused the problem. I just didn’t have this issue 5 months ago. This video shows the problem. https://youtube.com/shorts/c8z2x_gY1JU?si=PklO24NzO_1eMegs

**Comment by dinkc64** [comment] 2024-09-20 05:15
Hi,
Can you check to see how recent your fbneo installation is?
I think we made a fix for this maybe a year or 2 ago, but, my memory fails me sometimes
in config/games/centiped.ini, can you check to see the value of "analog" - is it 0x0100?  (it's near the top of the file)

best regards,
- dink

**Comment by barbudreadmon** [comment] 2024-09-20 05:32
The libretro port doesn't use the .ini files, everything was converted for usage through the libretro api. That value is set through the "Analog Speed" core option.

I think there are several frontend settings that could affect analog behavior, like retroarch's input driver or analog sensitivity. I'll do some checks later today to make sure everything is fine with default settings.

**Comment by barbudreadmon** [comment] 2024-09-20 07:10
@dinkc64 I think the range of values returned by `CinpMouseAxis` in the libretro port is too low.
Libretro returns polled values in the +/- 700 range, and i'm almost launching my mouse to get values that high. On a more normal usage (yet already moving a lot) i stay in the +/- 120 range.

After multiplying that value by the default 0x100 for `nAnalogSpeed` then dividing by the 10 `nInputIntfMouseDivider`, i end up with values that are very far from the min/max -32768/32767 for nMouse.

What's the range of values in standalone returned by `CinpMouseAxis` ? I think the libretro port probably needs some kind of coefficient here.

**Comment by dinkc64** [comment] 2024-09-20 13:14
@barbudreadmon 
printing Cinpmouseaxis, I get: 
-[0..3] +[0..3] moving the mouse very slowly
+-254 moving it fast as hell
20-30 making a fast circle

I wonder if the problem is happening somewhere else?

in intf/inp_interface.cpp: under GIT_MOUSEAXIS case:
				INT32 nMouse = CinpMouseAxis(pgi->Input.MouseAxis.nMouse, pgi->Input.MouseAxis.nAxis) * nAnalogSpeed;

Maybe nAnalogSpeed is not 0x100 by default? or.. um, wait, you already mentioned that.

Ok, so this; at the end of GIT_MOUSEAXIS in inp_interface.cpp:
				pgi->Input.nVal = (UINT16)nMouse;
				bprintf(0, _T("%d\n"), pgi->Input.nVal);
shows:
25-76 for slow movement
100-400 for normal movement
512-3000 for superfast movement

best regards,
- dink

**Comment by barbudreadmon** [comment] 2024-09-20 13:49
Those values don't seem that far from mine, and i just tried centiped on the MAME libretro core and it didn't seem faster there, so maybe i'm just overthinking this ? 
The "slowiness" on my side doesn't seem as bad as in the video with the trackball tbh, i can almost move from one border to the other without leaving my mouse mat.

@WillRussellFoley Make sure `Quick Menu > Core Options > Analog Speed` is not set to a low value for some reason ? Maybe test higher values until you find a comfortable one ?

**Comment by barbudreadmon** [comment] 2024-09-20 14:16
Ok, i just noticed i can actually move from one border to the other without leaving my mouse mat if i run RA in windowed mode, so it seems RA is doing weird stuff behind the scenes depending on video is scaled...

**Comment by barbudreadmon** [comment] 2024-09-20 14:49
@WillRussellFoley Is that a crt you are using ?

If not, can you do a quick test ? IIRC retropie has an optional menu you can access when launching games, that menu allows to change resolution. Does reducing the resolution somehow increase the speed of your trackball ?

**Comment by WillRussellFoley** [comment] 2024-09-20 17:38
> Hi,
> 
> Can you check to see how recent your fbneo installation is?
> 
> I think we made a fix for this maybe a year or 2 ago, but, my memory fails me sometimes
> 
> in config/games/centiped.ini, can you check to see the value of "analog" - is it 0x0100?  (it's near the top of the file)
> 
> 
> 
> best regards,
> 
> - dink

Hi, I recently updated FBNeo a month ago after it was fixed to work with the game Punch Out. As far as the other details, could you go a little more in depth about the instructions? I'm still not as tech savvy with the files and settings.

**Comment by WillRussellFoley** [comment] 2024-09-20 17:41
> @WillRussellFoley Is that a crt you are using ?
> 
> 
> 
> If not, can you do a quick test ? IIRC retropie has an optional menu you can access when launching games, that menu allows to change resolution. Does reducing the resolution somehow increase the speed of your trackball ?

Yes. I'm using an old PC VGA CRT monitor for the retro vibe.

I'll go into those quick menu settings and check the analogue settings you mentioned. I'm still not as tech savvy so bear with me.

**Comment by barbudreadmon** [comment] 2024-09-21 23:09
I tested windows today, and it turns out the situation is worse than i thought.
Both the standalone builds and the libretro port are fine, i'd say the speed with them is roughly 3 times what i experienced on linux (i can get from one border of centiped to the other with half my mouse mat).

So it turns out it is a retroarch problem where OS/drivers are inconsistent.
For now i recommend setting analog speed to 300% in the core options, until retroarch fix those inconsistencies between OS/drivers.

**Comment by barbudreadmon** [comment] 2024-09-23 14:49
I opened an issue about this at https://github.com/libretro/RetroArch/issues/17028

I'll close this one since it is more of a frontend problem.

**Closed by barbudreadmon** 2024-09-23 14:49 UTC
