### ISSUE TITLE
Recording input at slower cpu speed

### ISSUE THREAD

**Issue by norman0093** [finalburnneo/FBNeo#1073] opened 2022-06-17 09:38 UTC
Hello everyone,

I'm using FinalBurn Neo v1.0.0.02.

I want to record some games at 50% of cpu speed to make a kind of TAS.

Everything's fine during the recording, but when I replay it at normal cpu speed, the inputs are always out of sync (it's ok when I play back at same cpu speed).

Did I miss some settings or it's just what it is?

Any advice or help will be appreciated. 

Thank you.

**Comment by barbudreadmon** [comment] 2022-06-18 07:53
duplicate of https://neo-source.com/index.php?topic=3942.0

**Closed by barbudreadmon** 2022-06-18 07:53 UTC
