### ISSUE TITLE
segasonic the hedgehog music to fast

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#983] opened 2022-04-09 18:55 UTC
hello 
I just wanted to tell you that the segasonic the hedgehog game music is too fast
please would you be so kind to correct the speed of the music thanks

**Comment by barbudreadmon** [comment] 2022-04-10 06:29
I believe someone already reported this last year, and it was determined the speed was correct by comparing waveforms or something. Maybe @dinkc64 will remember better than me.

**Comment by juan200213** [comment] 2022-04-14 00:38
I already compared it with mame and the original soundtrack and it has a slower rhythm

**Comment by dinkc64** [comment] 2022-04-14 04:59
please give link to arcade pcb recording for comparison

**Comment by barbudreadmon** [comment] 2022-04-14 05:46
I believe there is indeed an issue, i found [this pcb video](https://www.youtube.com/watch?v=zNGZ8XIMcWM), in the intro when sonic is swallowed, i think FBNeo's music is a tad ahead of the pcb's.

**Comment by dinkc64** [comment] 2022-04-14 15:18
sorry, I didn't mean to close this report - it was an accident :)
I will look into this soon!

best regards,
- dink

**Comment by dinkc64** [comment] 2022-04-14 15:53
juan200213, thank you for the bug report, the problem is fixed now :)

best regards,
- dink

**Closed** 2022-04-18 23:00 UTC
