### ISSUE TITLE
Double axl (dblaxle) buttons problem

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1692] opened 2024-02-24 16:33 UTC
In double axl (dblaxle) only the accelerator button works.

**Comment by barbudreadmon** [comment] 2024-02-24 18:41
Only 1 of the 6 buttons didn't seem to work (confirmed through input test in service menu), it should be fixed with https://github.com/finalburnneo/FBNeo/commit/9a1c923587e21ec55a0843a8f9924dca011bb999

There might still be something wrong with the reverse/back button though, the input is on by default and becomes off when pressing, maybe it should be the other way around ? I'm not sure i understand how this game is played tbh...

**Comment by barbudreadmon** [comment] 2024-02-25 19:35
>There might still be something wrong with the reverse/back button though, the input is on by default and becomes off when pressing, maybe it should be the other way around ?

I checked and this behavior is exactly the same in MAME, so i'll assume it's intended.
Closing.

**Closed by barbudreadmon** 2024-02-25 19:35 UTC

**Comment by kounabi22** [comment] 2024-02-25 22:13
The gear shift button works incorrectly,
the Low gear act as high and the high as Low.

**Comment by barbudreadmon** [comment] 2024-02-26 06:51
Well, again, i don't understand how this game is played, the only thing i can tell is that the current behavior matches MAME, so i'd rather leave things as-is.
Note that there is a dipswitch to change the behavior of that gear shift.

**Comment by dinkc64** [comment] 2024-02-27 14:54
shifter modified to match the defaults in the dips

**Comment by kounabi22** [comment] 2024-02-27 15:02
yes i change the dip option and now its ok.
