### ISSUE TITLE
item error in kovpluststd and kovplushsqj

### ISSUE THREAD

**Issue by khanhnguyen1988** [finalburnneo/FBNeo#1366] opened 2023-03-04 09:20 UTC
All items are X9 selectable, except for the 4 swords. In the old FBNEO version @taoenwen sent me without this problem
https://www.mediafire.com/file/ng6ao45g3b6dlls/Videos.zip/file
https://www.mediafire.com/file/vu7ffmhwtehm6pn/error+chỉnh+videos.zip/file

**Comment by dinkc64** [comment] 2023-03-05 05:44
can you make inputs recording:
Game -> Replay -> Record Input
"from power on  w/NVRAM", use working version from taoenwen. :)
get X9 item then stop recording.

I need recording to help figure out the problem

best regards,
- dink

**Comment by khanhnguyen1988** [comment] 2023-03-05 06:46
Yes ! i have recorded . https://www.mediafire.com/file/evo53wdac1abv36/fbneo+taoenwen.zip/file

**Comment by taoenwen** [comment] 2023-03-05 15:44
@khanhnguyen1988 Try this version.
[fbneo.zip](https://github.com/finalburnneo/FBNeo/files/10892184/fbneo.zip)

**Comment by khanhnguyen1988** [comment] 2023-03-05 17:22
@taoenwen this fbneo version is very good. Fixed B+C button bug when picking up items
![Untitled](https://user-images.githubusercontent.com/96006482/222975720-76c0672d-cdd8-4e59-a6ad-a4572510b6db.png)
![Screenshot 2023-03-05 234411](https://user-images.githubusercontent.com/96006482/222975726-26ef4acf-8bea-4aed-adb5-d34336d8340e.png)
![Screenshot 2023-03-06 001304](https://user-images.githubusercontent.com/96006482/222975741-d98fd735-cf98-4299-a085-267873315637.png)
![Screenshot 2023-03-06 001235](https://user-images.githubusercontent.com/96006482/222975747-db3e2432-4969-4a41-bb39-5411e26d35d5.png)

**Comment by taoenwen** [comment] 2023-03-06 15:06
@khanhnguyen1988 Hi, khanhnguyen1988, The issue of items has been solved. https://github.com/finalburnneo/FBNeo/commit/d4bfb000e81a1e531eeb594e073f4567f0c56bad
test : https://github.com/finalburnneo/FBNeo/releases/tag/latest
If the issue is confirmed to be resolved, please close it, thanks!

**Closed** 2023-03-06 16:18 UTC
