### ISSUE TITLE
Adding a touchscreen input mode for lightgun games on Retroarch core.

### ISSUE THREAD

**Issue by illando** [finalburnneo/FBNeo#1818] opened 2024-06-25 10:50 UTC
I tried to play lightgun games on both iOS and Android version of the RA core using the touchscreen.
It seems impossible using any of the actual Control Device Type settings.
The pointer setting is able to snap the pointer to the tap position, but fire and reload are still connected to the retropad touchscreen overlay buttons.

It would be nice to add a new Device Type setting specific for touchscreen like other RA cores have.
The MAME core works great on iOS for example... it supports the following bindings, so it's possible to play using only the touchscreen.

1 finger tap -> Fire
2 fingers tap -> Reload
3 fingers tap ->  Start
4 finders tap -> Insert coin

Thanks in advance.

**Comment by barbudreadmon** [comment] 2024-06-25 10:55
>Device Type setting specific for touchscreen

Retroarch doesn't have such a thing. In all likeliness, on ios/android you must use the "pointer" device type. If it doesn't work, it's a setup issue and i'd recommend asking support from the retroarch team.

**Comment by illando** [comment] 2024-06-25 11:18
As you can see from the screenshot. the MAME core has a specific touchscreen setting in Core Option > Input.
Activating that setting makes the bindings I described before automatically active.
There's no way to bind the taps to the controls... in Mame, the Gun trigger and Gun reload are assigned to Mouse 1 and Mouse 2 button in Settings > Input >  Retropad Binds > Port 1 controls.

![Screenshot_20240625-130824](https://github.com/finalburnneo/FBNeo/assets/11694410/3bf319b1-48c8-45b1-a22d-d42ab21c442f)

![Screenshot_20240625-131604](https://github.com/finalburnneo/FBNeo/assets/11694410/799ccc3f-844b-4f5d-879c-f6323e3945a0)

**Comment by barbudreadmon** [comment] 2024-06-25 12:04
Ok, i think i had misunderstood your issue.

So you do confirm that the "pointer" device type does control the target on mobile phones ? It does seem to match with what i see for that "touchscreen" core option in libretro MAME's source code ([here](https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/libretro.cpp#L413-L414) and [here](https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_retro.cpp#L893-L896)).
Inputs are indeed binded by default to the retropad model with our "pointer" device type (see [documentation](https://docs.libretro.com/library/fbneo/#mapping)). 

I don't know how you remap the retropad model to touchscreen events since i'm far from being an expert about retroarch, especially on mobile phones. Again, my recommendation would be to get in touch with the retroarch team about this.

If they tell you that kind of remapping is impossible, then i'll see what can be done on core's side to get around this.

**Comment by illando** [comment] 2024-06-25 14:29
@barbudreadmon I have an update:

Yes: I can confirm that the "pointer" device type of FbNeo does control the target on mobile phones. But fire, reload, coins and 1P start are still connected to to retropad... su after tapping the position, on the screen, the only way to make it works is to press at the same time the Fire button on the retropad.

Also: (on iOS only and not on Android) the Lightgun device type of FbNeo is almost working. You can fire in the point of the screen you touch, but the retropad is disconnected so you have to switch to Retropad device type to start the game adding coins and pressing 1P button, and than switch back to Lightgun device type to play the game (and still.. you can not reload).

Maybe... RA is already passing to the core the touchscreen input but the core is not set to receive it.
I forgot to mention that Mame also has this configuration.. where the button are assigned to the gun input.
Is there an equivalent menu in FBNeo?

![Screenshot_20240625-162441](https://github.com/finalburnneo/FBNeo/assets/11694410/34ac4ec9-22ed-49e5-8559-de52943866fd)
![Screenshot_20240625-162501 (1)](https://github.com/finalburnneo/FBNeo/assets/11694410/5c696e83-0660-458c-8d40-387e6a41394c)

**Comment by barbudreadmon** [comment] 2024-06-25 14:55
>Is there an equivalent menu in FBNeo?

No, the MAME OSD belongs to MAME.

I repeat : 
I don't know how you remap the retropad model to touchscreen events since i'm far from being an expert about retroarch, especially on mobile phones. Again, my recommendation would be to get in touch with the retroarch team about this. If they tell you that kind of remapping is impossible, then i'll see what can be done on core's side to get around this.

**Comment by illando** [comment] 2024-06-25 15:16
Ok, thanks... sorry I though proving more details would help to find a solution.

**Comment by barbudreadmon** [comment] 2024-06-25 15:43
Retroarch's job includes remapping, that's the whole purpose of using a frontend to handle those tasks. 
Sure, it should be possible to add another device type to preset the mapping to touchscreen events, but i wouldn't be able to give any ETA about this, hence why i recommend asking the retroarch team since it's supposed to be retroarch's job to handle remapping in the first place.

**Comment by barbudreadmon** [comment] 2024-06-30 07:25
@illando so did you figure out if remapping retropad buttons to touchscreen events through their frontend is possible ?

**Comment by illando** [comment] 2024-06-30 18:59
@barbudreadmon i’m still trying but I did not have time to open an issue on RA github.
I’ll try in the next days.

**Comment by barbudreadmon** [comment] 2024-06-30 21:21
Hmmm ok, i'll have to implement a device type for this if remapping the buttons through their frontend is not obvious.

**Comment by illando** [comment] 2024-07-01 07:44
It seems to be not so obvious, because if I try to map the various type of touch from Settings > Input > Retropad Binds > Port 1 controls and it doesn’t recognize any difference from single finger, double finger,  triple and 4 fingers. So it seems impossible if it’s not preassigned by a proper core device type.
Maybe that’s why other cores got a specific device type for touchscreen lightgun.
I remember that @yoshisuga took care of the touchscreen implementation on iOS some time ago, and I already contacted him.
I’m almost new on the android side, but since when I bought an android device (one month ago) the touchscreen functionality was perfect on the other cores, I suppose since when he implemented this function on iOS it started working also on android.
I know you already checked the Mame core source code but I can tell you that also the BeetleSaturn core works perfectly, with reload start and select implemented. Maybe you can also check that code. 🙂

**Comment by barbudreadmon** [comment] 2024-07-01 08:26
Okay, meaning their remapping implementation for touchscreen events is incomplete... 
Well, i'll try to look into this soon.

**Comment by barbudreadmon** [comment] 2024-07-06 06:52
I tried implementing that "touchscreen" device type in https://github.com/libretro/FBNeo/commit/9e7f2030ad0ce2fc9150ea73e6507bf932ad017c

Keep in mind i can't test this, so it's entirely possible that it doesnt work.

Also, as mentioned in my documentation, i decided to leave non-gameplay buttons like Start/Coin on retropad.

**Comment by illando** [comment] 2024-07-06 18:12
Hi @barbudreadmon! Thanks a lot!!!

I tested only Android for the moment (is not possible to update cores in iOS, you have to wait the next RA release on app store do do it) with various games and everything seems working great, on games that uses 2 fingers touch for reload or for bombs, and for games with continuous fire.
The only exception is Zombie Raid (zombraid.zip), it’s strage because it works using mouse. The problem is that when you tap on the screen it only moves the pointer on that position but it doesn’t fire!

There are only 2 small improvements you can implement at this point:
- in core options > Crosshair emulation, you could add the touchscreen device to the “hide with lightgun device”.
- I’m running RA on an android retrohandled device emulating lightgun games with touchscreen and switching to mouse when the handled is connected to the TV. It seems that FBneo needs to be reset to switch from one device mode to another, so I have to switch it, save the controller configuration and reset the game. Could be possible to make it switchable on the fly?

**Comment by barbudreadmon** [comment] 2024-07-07 08:49
I added touchscreen to the devices that automatically hide the emulated crosshair since it does make sense.

As for your 2 other issues, i can't make much sense of them : 
- On my desktop, i can change device types on the fly how many times i want, and they'll always be accounted without having to reset, so this behavior being something on core's side seems extremely unlikely. Maybe that's something specific to retroarch android/ios ? Either way, i don't think i'll be able to debug what i can't reproduce.
- There doesn't seem to be anything that could explain the zombraid issue, that game is using button 1 to fire, and that button is what i map to "1 tap" with the "touchscreen" device type (and to the left click of the "mouse (full)" device type). If it doesn't work for zombraid then i can't understand why it would work anywhere else. While searching for the non-existing documentation about that clunky libretro touchscreen stuff, i discovered that [flycast doesn't use the "1 tap" event for fire, it uses the "pressed" event instead](https://github.com/flyinghead/flycast/commit/4514a4bfccf3b29531d58a85e3d5c00e75d58526), so maybe that "1 tap" event is somehow unreliable despite their MAME core seemingly using it ? I decided to give this a try.

I pushed the following changes : https://github.com/libretro/FBNeo/commit/5088fd6120dd73f532a795762f0dfd97f70fc65c. 
Let's hope they won't make things worse.

**Comment by illando** [comment] 2024-07-09 15:22
Hi @barbudreadmon:
the automatic hiding of the crosshair is working great now, and I can confirm that is now possible to change device types on the fly!
Maybe the new "pressed event" solved it, because after switching back to touchscreen device fire was not working before.

Unfortunately, zombraid still have the same problem, but it's also present on MAME core using the touchscreen device.
So I can say it's only related to this game.
It's trange, but It seems zombraid doesn't like to receive the coordinates of the crosshair + the fire input all together, when they are both assigned to the touchscreen tap.
I did a test by keeping the finger on the screen and pressing the B button to fire and it's working (in some way).
Maybe the mouse device works because the position of the crosshair is controlled by the mouse movement and the fire command is assigned to the left click.

**OFFTOPIC:**
I see that 2 lightgun roms are not included i the FBneo working list: le2.zip and ptblank2.zip.
As they are very similar to  their respective prequel game (that runs both perfectly), would be possible to add them?

Thanks again.

**Comment by barbudreadmon** [comment] 2024-07-09 15:41
Where does the crosshair go when you stop touching the screen ? Does it stay where you touched last ? Does it go elsewhere ?
If the coordinates are somehow reset to 0,0 when you stop touching the screen, it *might* be a problem where the game activates the trigger before updating the coordinates.

>I see that 2 lightgun roms are not included i the FBneo working list: le2.zip and ptblank2.zip.

We don't accept requests for currently unsupported hardware.

**Comment by illando** [comment] 2024-07-09 18:00
When I stop touching the screen the crosshair goes to the center of the screen.
It does exactly what you described… it keeps shooting in the center of the screen!

**Comment by barbudreadmon** [comment] 2024-07-10 06:15
Hmmm, only updating coordinates while the touchscreen is pressed would be easy to implement. However it wouldn't really fix the main problem, which seems to be that the game registers the state change of the trigger before the gun position.

Maybe we could buffer the trigger for 1(?) frame, artificially creating some sort of input lag, but i'm neither sure if it's a good idea nor if it's the only solution.
@dinkc64 any idea ?

**Comment by dinkc64** [comment] 2024-07-10 13:29
I would hold the coords and trigger for 3-4 frames.   Hitting a button on a controller or kbd - as fast as I can hit and release one - is held for at least 4 frames. (if memory serves me...)

best regards,
- dink

**Comment by barbudreadmon** [comment] 2024-07-10 14:39
I'm not too sure holding trigger would help ?

I *think* the game sees trigger activation and coords update in reverse order ? Is it possibly some problem with irq generation from `Drv68kNoSubFrameCallback` ?
Actually, the game feels extremely sluggish with a mouse on my side when using its current `Drv68kNoSubFrameCallback`, something like 
```
static void Drv68kZombraidCallback()
{
	INT32 nInterleave = 262;
	INT32 nCyclesTotal[1] = { (cpuspeed * 100) / refresh_rate };
	INT32 nCyclesDone[1]  = { 0 };

	SekOpen(0);

	for (INT32 i = 0; i < nInterleave; i++)
	{
		CPU_RUN(0, Sek);

		if (i == 4 && nCurrentFrame & 2)
			SekSetIRQLine(2, CPU_IRQSTATUS_AUTO);

		if (i == (nInterleave - 1))
			SekSetIRQLine(1, CPU_IRQSTATUS_AUTO);
	}

	SekClose();

	if (pBurnSoundOut) {
		x1010_sound_update();
	}
}
```
seems to produce better results ?

**Comment by dinkc64** [comment] 2024-07-10 20:42
What game is it?

**Comment by illando** [comment] 2024-07-10 21:55
@dinkc64 “zombraid” - Zombie Raid
Thanks!

**Comment by dinkc64** [comment] 2024-07-11 00:46
illando, thanks

barbudreadmon, that makes it worse here, since it only updates the cursor on frame#&2

**Comment by dinkc64** [comment] 2024-07-11 00:54
I've tried just about everything I could think of, and it seems like there is no way to get around the fact that the game wants at least 2 frames to update the analog positionals.

best regards,
- dink

**Comment by illando** [comment] 2024-07-11 05:36
Does it mean the game can’t be fixed?

**Comment by dinkc64** [comment] 2024-07-11 05:47
no, it means sir barbudreadmon will have to impl. it slightly differently, for example:
on press: start timer.
frame 0: do nothing (but update analog controls to destination)
frame 1: do nothing (but update analog controls to destination)
frame 2: press fire

best regards,
- dink

**Comment by barbudreadmon** [comment] 2024-07-11 05:57
Apparently i have some kind of issue on my setup when using a mouse as analog axises in retroarch

>on press: start timer.
frame 0: do nothing (but update analog controls to destination)
frame 1: do nothing (but update analog controls to destination)
frame 2: press fire

Do you mean directly in the seta driver ? I don't think that would be a good idea in the frontend since i'd have to save stuff in states

**Comment by dinkc64** [comment] 2024-07-11 13:05
since this is probably not the only game that has input lag with the x/y coords, and this feature is basically a new input type it would make sense to put it on the interface side.  It shouldn't be too difficult?  I would imagine something like this would work with every game across the board:
```
int i_timer = 0;
newinput_fire {
  update_xy_coords();
  i_timer = 3;
}

runframe_libretro() {
  if (i_timer > 0) {
     update_xy_coords();
     i_timer--;
     if(i_timer == 0) {
        hit_button();
     }
  fbneo_runframe();
}

**Comment by barbudreadmon** [comment] 2024-07-11 13:44
Well, i have some vague idea on how i could implement a timer feature to my inputs in the interface code, but i don't think it would work properly with runahead and the likes, hence why that's something i'd rather avoid.

Let's just give up on this since there is no satisfying solution.

**Comment by illando** [comment] 2024-07-11 14:50
sorry for my ignorance @barbudreadmon  (I'm not a developer), is not possible to modify only the driver of that game?

**Comment by barbudreadmon** [comment] 2024-07-11 15:58
>is not possible to modify only the driver of that game?

Everything is possible, and that specific one was my first plan, but it is unsatisfying, just like the other one.

**Comment by illando** [comment] 2024-07-11 20:56
Ok, I got it.
BTW thanks for implementing this new device.
It works perfectly with the rest of the games I tested! 🙂

**Comment by barbudreadmon** [comment] 2024-07-12 06:56
I slightly improved the code : https://github.com/libretro/FBNeo/commit/143452d376faf0090d40241c71cc9b532b0605e0
Now the position shouldn't reset when you stop pressing your screen, meaning it should be possible to shoot at the correct position in zombraid by touching twice in a row ? You'll be using 2 shots though.

**Comment by illando** [comment] 2024-07-12 17:58
@barbudreadmon Yes I can confirm, zombieraid works exactly as you predicted. It’s not easy to play like that because it doesn’t fire as aspected on the first tap… but it’s playable.
The other games are not affected and still works fine!

**Comment by barbudreadmon** [comment] 2024-07-13 05:25
Ok, i'll be closing soon then.

**Comment by illando** [comment] 2024-07-13 07:51
@barbudreadmon yes, in my opinion you should just think again about the decision of keep the select and start assigned to the retropad when this new thouch device is active.
As I’m playing with and Android retro handled device this is not a problem of mine, as I have physical Select and Start buttons near the touchscreen, but of you are playing on a smartphone or a tablet you have to continuously toggle on/off the touchscreen control overlay to insert coins and press start.
Binding these 2 inputs to 3 and 4 fingers taps as the other cores are doing gives the smartphone and tablet users the ability to play easily.

Maybe you could keep both touchscreen and retropad bindings as you did for fire and reload.

**Comment by barbudreadmon** [comment] 2024-07-13 10:21
Gameplay is not limited to trigger/reload in arcade gun games, some have additional buttons to launch bombs or do other things, mapping start/coin to tap events instead of those gameplay buttons doesn't seem like a sane decision.
I don't know what other cores are doing, but tbh it seems irrelevant.

>you have to continuously toggle on/off the touchscreen control overlay to insert coins and press start.

I thought it was possible to use an overlay and the touch events at the same time, it's not ? It seems like a problem you should submit to the retroarch team.

**Comment by illando** [comment] 2024-07-13 12:20
@barbudreadmon makes sense!
I really don’t understand why the touchscreen controls are not managed by RA at general level and instead all the cores developed decided to implement it by themselves.
It would be easier if RA could mange the touchscreen in the general setting allowing users to decide the various bindings per game or per system.

**Comment by dinkc64** [comment] 2024-07-13 13:12
RA doesn't make sense in a lot of things it does, but mainly I think the limitations are due to the fact that it supports too many systems.  To put it bluntly, I've used different ui's over the years, and have been using ibm PC since 1989.  In fact, nothing has aggravated me as much as RA's ui - there were times where I literally wanted to punch the monitor.  Unfortunately, there isn't a real alternative for touchscreen devices...

**Comment by barbudreadmon** [comment] 2024-07-13 13:28
RA is a fork of bsnes, it was originally meant to play snes on PS3. Many decisions come from the fact it was originally meant to be a gamepad-to-gamepad mapping only, and nobody is too eager to revise the entire thing.

**Comment by dinkc64** [comment] 2024-07-13 20:41
@barbudreadmon do you know if the machine the forum is on is alright? 
It seems unresponsive right now :(

**Comment by barbudreadmon** [comment] 2024-07-13 23:26
It's back

**Comment by dinkc64** [comment] 2024-07-14 00:13
![rise](https://github.com/user-attachments/assets/9109eddc-ce69-4bf6-9f27-503769f7caba)

You used the 'ole "rise from your grave trick", eh?  :)

**Closed** 2024-07-19 14:34 UTC
