### ISSUE TITLE
Some not working games that works on Mame2010.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#56] opened 2019-06-17 06:32 UTC
I tested some games that i usually run with mame2010 core.

fbneo has issues on these:

afighter >> strange blue screen, don't work
bagman >> works but the screen is translated right
dotron >> works but lacks some commands and seems there's a button stuck
enduror >> strange screen and don't work
gemini >> same above

Hope they will be fixed soon, thanks.

**Comment by barbudreadmon** [comment] 2019-06-17 08:00
What's your platform ? Did you follow the instruction from https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/README.md ?

> Don't report issues if you didn't build a valid romset.

afighter >> strange blue screen, don't work >> **it works for me, bad romset for you ?**
bagman >> works but the screen is translated right >> **yes, it seems there is the same issue with parent & clones**
dotron >> works but lacks some commands and seems there's a button stuck >> **i don't know how this game is played, so i can't confirm, at the very least all controls available from the `InputList` seems mapped, did you check the controls in RA's quick menu ?**
enduror >> strange screen and don't work >> **it works for me, bad romset for you ?**
gemini >> same above >> **i'm getting a black screen with the parent, the clones work**

**Comment by fastpop72** [comment] 2019-06-17 08:12
> What's your platform ? Did you follow the instruction from https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/README.md ?
> 
> > Don't report issues if you didn't build a valid romset.
> 
> afighter >> strange blue screen, don't work >> **it works for me, bad romset for you ?**
> bagman >> works but the screen is translated right >> **yes, it seems there is the same issue with parent & clones**
> dotron >> works but lacks some commands and seems there's a button stuck >> **i don't know how this game is played, so i can't confirm, at the very least all controls available from the `InputList` seems mapped, did you check the controls in RA's quick menu ?**
> enduror >> strange screen and don't work >> **it works for me, bad romset for you ?**
> gemini >> same above >> **i'm getting a black screen with the parent, the clones work**

I use a PC installed with Debian9 x64 and retropie.

I just checked the afighter romset and i spotted that i have 1 file of the romset with different CRC, so it's my problem.

Probably the core doesn't check CRC before launching a game? it only checks the filenames & sizes?

I will test these games with correct romset and i will let you know. Thanks.

**Comment by barbudreadmon** [comment] 2019-06-17 08:34
> Probably the core doesn't check CRC before launching a game? it only checks the filenames & sizes?

It checks everything, however if a file has the right name with the wrong crc, it will only print a warning in logs, something like this : `[libretro WARNING] [FBNEO] Using ROM with bad CRC and name %s from archive %s`

**Comment by fastpop72** [comment] 2019-06-17 10:46
> > Probably the core doesn't check CRC before launching a game? it only checks the filenames & sizes?
> 
> It checks everything, however if a file has the right name with the wrong crc, it will only print a warning in logs, something like this : `[libretro WARNING] [FBNEO] Using ROM with bad CRC and name %s from archive %s`
> 
> Also, afaik, we aren't missing any controls for dotron, the game is 4 buttons + dpad + dial + trackball, all of them are mapped (dial + trackball are on the right analog stick by default). If you think the way i map them by default is wrong, let me know, idk the game.

So:

afighter >> works (i had wrong romset)
enduror >> works (same)
bagman >> nothing to do at the moment, will use mame2010
gemini >> i revert using geminib (working bootleg on fbneo)

dotron has issues, commands are mapped ok but there's a bug: The player has "deflect" always on (like there were the Button 2 stuck!) so it can't move around and throw discs.

I already checked dotron roms and i have the correct set (name & CRCs OK).

**Comment by dinkc64** [comment] 2019-06-17 16:02
Hi,
Regarding bagman, dotron and gemini wing - I'll have a fix tonight :)  Sorry about the problems!!

best regards,
- dink

**Comment by dinkc64** [comment] 2019-06-18 00:33
Hi,
I just checked in fixes for bagman, discs of tron and gemini wing.  Please let me know if they solve the problems.

thank you for finding / reporting these bugs & best regards,
- dink

**Comment by barbudreadmon** [comment] 2019-06-18 06:35
It seems fixed for me

**Comment by fastpop72** [comment] 2019-06-18 12:22
> Hi,
> I just checked in fixes for bagman, discs of tron and gemini wing. Please let me know if they solve the problems.
> 
> thank you for finding / reporting these bugs & best regards,
> 
> * dink

Sorry for delay but i had to wait the update of the libretro branch to test.

bagman and gemini now works and dotron can be played correctly! THANKS!!!

I'd like to point some other games to your attention:

jedi >> start but seems there's a command stuck, at the start the player goes left and can't be moved.
ringking >> start but it stucks at the white grid, the parent rom kingofb works OK instead!
kinst & kinst2 >> works well but "Freeplay" is set by default and can't be deactivated.

Thanks.

**Comment by barbudreadmon** [comment] 2019-06-18 13:33
> jedi >> start but seems there's a command stuck, at the start the player goes left and can't be moved.

Good catch, it seems to be happening only on 1st boot & game though, the issue is reproducable by starting a game after deleting `jedi.fs`

> ringking >> start but it stucks at the white grid, the parent rom kingofb works OK instead!

I confirm

> kinst & kinst2 >> works well but "Freeplay" is set by default and can't be deactivated.

While they run pretty well, emulation of those is still kinda preliminary, not sure the driver will get a lot of improvements as long as @zxmarcos isn't around.

**Comment by fastpop72** [comment] 2019-06-18 20:28
I add these to the list:

maxrpm >> starts in test mode and the Start1 & Start2 button are not mapped
pkladies >> the five buttons to "held" the cards are not mapped.
qix >> only on 1st boot you can't select language because TEST button is not mapped, on 2nd boot the game starts correctly but in English only.

Thanks...

**Comment by barbudreadmon** [comment] 2019-06-18 22:02
> pkladies >> the five buttons to "held" the cards are not mapped.
qix >> only on 1st boot you can't select language because TEST button is not mapped, on 2nd boot the game starts correctly but in English only.

Those 2 are libretro specific : 
- i never handled mahjong inputs, pkladies is using those, honestly i don't know how to deal with them...
- this game is a bit troublesome, it seems to be using 4 different test buttons...

**Comment by dinkc64** [comment] 2019-06-19 02:12
jedi, on the first run/first game on this hw player's ship will go out of control, this is just how the game is programmed - I think it is doing some sort of internal calibration with the analog sticks.

qix, (barbudreadmon) you'll need to map all of those service buttons, I know it seems crazy - the original hw has the buttons hidden in the coin door :)

maxrpm, emulation is not finished on this game.  I'll make a note of it :)

barbudreadmon, regarding mahjong, perhaps map the keys similar to mame or fb standalone?

king of boxer / ring king: all games fixed related to this driver

best regards,
- dink

**Comment by fastpop72** [comment] 2019-06-19 13:16
> jedi, on the first run/first game on this hw player's ship will go out of control, this is just how the game is programmed - I think it is doing some sort of internal calibration with the analog sticks.
> 
> qix, (barbudreadmon) you'll need to map all of those service buttons, I know it seems crazy - the original hw has the buttons hidden in the coin door :)
> 
> maxrpm, emulation is not finished on this game. I'll make a note of it :)
> 
> barbudreadmon, regarding mahjong, perhaps map the keys similar to mame or fb standalone?
> 
> king of boxer / ring king: all games fixed related to this driver
> 
> best regards,
> 
> * dink

Thanks for the ringking fix!!

I add this game:

stargrds >> both "move" and "shoot" are mapped to same stick, the games need two separate sticks like the controls of the "sdi" rom.

Thanks.

**Comment by barbudreadmon** [comment] 2019-06-19 14:22
> stargrds >> both "move" and "shoot" are mapped to same stick, the games need two separate sticks like the controls of the "sdi" rom.

Thanks for the report, that one is libretro specific too, i'll try to fix it and at least the qix one tonight. 
NB : The mahjong games will need a bit of brainstorming first.

**Comment by barbudreadmon** [comment] 2019-06-19 14:28
@dinkc64 actually, do you mind if i replace 
```
	{"P1 Coin",		BIT_DIGITAL,	DrvJoy1 + 0,	"p1 coin"	},
	{"P1 Start",		BIT_DIGITAL,	DrvJoy1 + 2,	"p1 start"	},
	{"P1 Left Stick Up",	BIT_DIGITAL,	DrvJoy2 + 4,	"p1 up"		},
	{"P1 Left Stick Down",	BIT_DIGITAL,	DrvJoy2 + 5,	"p1 down"	},
	{"P1 Left Stick Left",	BIT_DIGITAL,	DrvJoy2 + 6,	"p1 left"	},
	{"P1 Left Stick Right",	BIT_DIGITAL,	DrvJoy2 + 7,	"p1 right"	},
	{"P1 Right Stick Up",	BIT_DIGITAL,	DrvJoy2 + 0,	"p3 up"		},
	{"P1 Right Stick Down",	BIT_DIGITAL,	DrvJoy2 + 1,	"p3 down"	},
	{"P1 Right Stick Left",	BIT_DIGITAL,	DrvJoy2 + 2,	"p3 left"	},
	{"P1 Right Stick Right",BIT_DIGITAL,	DrvJoy2 + 3,	"p3 right"	},
```
by
```
	{"P1 Coin",		BIT_DIGITAL,	DrvJoy1 + 0,	"p1 coin"	},
	{"P1 Start",		BIT_DIGITAL,	DrvJoy1 + 2,	"p1 start"	},
	{"P1 Left Stick Up",	BIT_DIGITAL,	DrvJoy2 + 4,	"p1 up"		},
	{"P1 Left Stick Down",	BIT_DIGITAL,	DrvJoy2 + 5,	"p1 down"	},
	{"P1 Left Stick Left",	BIT_DIGITAL,	DrvJoy2 + 6,	"p1 left"	},
	{"P1 Left Stick Right",	BIT_DIGITAL,	DrvJoy2 + 7,	"p1 right"	},
	{"P1 Right Stick Up",	BIT_DIGITAL,	DrvJoy2 + 0,	"p1 up 2"	},
	{"P1 Right Stick Down",	BIT_DIGITAL,	DrvJoy2 + 1,	"p1 down 2"	},
	{"P1 Right Stick Left",	BIT_DIGITAL,	DrvJoy2 + 2,	"p1 left 2"	},
	{"P1 Right Stick Right",BIT_DIGITAL,	DrvJoy2 + 3,	"p1 right 2"	},
```
?

**Comment by fastpop72** [comment] 2019-06-19 20:17
@barbudreadmon what do you mean when you say "libretro specific"?

**Comment by dinkc64** [comment] 2019-06-20 01:58
barbudreadmon, before we change any inputs we need to come up with a good and well-thought out solution to all the games that use this type of 2-joy stuff. 
For example:
d_williams: robotron
d_bwidow:  bwidow
do these games map fine?  should we change the mapping to be like these?

**Comment by barbudreadmon** [comment] 2019-06-20 02:38
@fastpop72 i mean it's a "frontend" issue, basically my algorythm parsing codebase's inputs to create mapping don't work well with those games because they are some kind of exceptions.

@dinkc64 they do because i added per-game rules for those 2, i could do the same here, but i also have a "catchall" rule when it's using something like "p1 up 2". i'm fine with both solutions, but i think it would be nicer with the "p1 up 2" thing, i noticed only "bullet" from sys16b is using those though. if we were to transform other game's szInfo, i guess i could remove a lot of exceptions.

**Comment by fastpop72** [comment] 2019-06-20 21:19
I add these games to check:

vangrd2 >> when you move the ship left and down the 'sprite' of the ship is reversed. OK in mame.
wndrplnt >> rom start but don't work (not yet implemented??)

Thanks...

**Comment by dinkc64** [comment] 2019-06-20 23:39
fastpop72, thanks - both vangrd2 & wndrplnt are fixed now :)

**Comment by barbudreadmon** [comment] 2019-06-21 05:16
qix and stargrds should also be ok.
For mahjong mapping i gave it some thoughts and opened a separate issue at https://github.com/libretro/FBNeo/issues/71

@dinkc64 should i normalize codebase by using the "pX up 2" stuff everywhere ?

**Comment by fastpop72** [comment] 2019-06-21 20:40
If you have time, there's a little tile-priority problem in mwalk. See attached screens from level 2.

![mwalk-06-21-203646](https://user-images.githubusercontent.com/32760152/59950118-53d40880-9475-11e9-8f0c-935318dd9151.png)
![mwalk-06-21-203455](https://user-images.githubusercontent.com/32760152/59950119-53d40880-9475-11e9-97e9-96ea622e92f1.png)
![mwalk-06-21-203600](https://user-images.githubusercontent.com/32760152/59950120-53d40880-9475-11e9-939b-1c59bab738b6.png)

**Comment by dinkc64** [comment] 2019-06-22 03:28
barbudreadmon, sure, if you want :)

**Comment by dinkc64** [comment] 2019-06-22 03:38
fastpop72, thanks for the continued bug reports!

**Comment by fastpop72** [comment] 2019-06-23 21:26
I add this game to the list:

thndrbld >> a button is missing to accelerate, there's mapped only a 'throttle' button but there must be a 'throttle+' and a 'throttle-' to accelerate and decelerate.

Anyway i can't get to properly work 'jedi', i have the same issue at each start.
The only way i found in order to play it is to keep pressed the 'd.pad right' at the difficulty selection screen until the DeathStar starts to move right, then when i select the difficulty level i can start the game without the issue. Could be because i play the game using an arcade joystick WITHOUT analog sticks?

**Comment by dinkc64** [comment] 2019-06-23 23:26
With thunderblade on fbn (not in libretro), you can, for example, map Z axis to throttle, and right trigger will be throttle+ and left throttle-.  Or, if you use a keyboard preset w/autocentering - it will use up/down/left/right arrows for control and v/f for throttle.  I'm not sure how this translates to libretro, though.

**Comment by dinkc64** [comment] 2019-06-23 23:39
Here's an except from Return of the Jedi's manual:
![jedi_manual](https://user-images.githubusercontent.com/12570148/59983468-029b5480-95ee-11e9-9c52-42bf7f3d9878.png)

To sum it up:
1: Load game, don't coin up or start game yet!
2: go around and circles a few times with your joystick
3: start a game, all should be well :)
NOTE: as with all old atari games with nvram, a game must be played and ended before it will fully save the settings.  After game ends, wait for the game goes to the titlescreen before exiting the emulation.

best regards,
- dink

**Comment by dinkc64** [comment] 2019-06-24 00:19
To make things a lot easier for everyone, I modified the jedi emulation to auto-calibrate the joystick first time it's loaded :)  To try it out, delete your nvram file for jedi and then load & start a game as usual.

best regards,
- dink

**Comment by fastpop72** [comment] 2019-06-24 06:08
> To make things a lot easier for everyone, I modified the jedi emulation to auto-calibrate the joystick first time it's loaded :) To try it out, delete your nvram file for jedi and then load & start a game as usual. (everything I said above about calibrating the stick can be ignored)
> 
> best regards,
> 
> * dink

Thanks @dinkc64 !!!

Anyway others steps you described was OK!! You were right.

**Comment by barbudreadmon** [comment] 2019-06-24 17:50
Oops, thndrbld (and aburner2) throttle fixed, i thought they had a speedup only throttle.

@dinkc64 Just making sure : gforce2 is using a speedup only throttle, right ?

**Comment by dinkc64** [comment] 2019-06-24 23:01
fastpop72, you're welcome :)  

barbudreadmon, yes, gforce2 is only for speedup

**Comment by barbudreadmon** [comment] 2019-07-05 14:33
the only remaining issue is the missing mahjong controls (https://github.com/libretro/FBNeo/issues/71), i'll close this one.

**Closed by barbudreadmon** 2019-07-05 14:33 UTC
