### ISSUE TITLE
FBneo -lixtinfo dat lost part of "merge" information, it cause split set to contain duplicate files

### ISSUE THREAD

**Issue by crashGG** [finalburnneo/FBNeo#1190] opened 2022-10-03 08:34 UTC
Take "captcommj" for example:
In the dat file exported by fbneo,the part pointed out  is missing the merge tag:
<img width="471" alt="1" src="https://user-images.githubusercontent.com/80488411/193535280-f69de660-878d-4b2b-b005-73f96f5f8f4e.png">

This is the rom dat exported by mame, you can see more duplicate files have merge tags:
<img width="526" alt="2022-10-03_113849" src="https://user-images.githubusercontent.com/80488411/193535339-7b6ec702-0074-4af0-88fe-7ad608c3b31e.png">

If you use cmpro to load a dat with missing merge tags and scan a game set, the clone set contains duplicate files with the main rom, causing unnecessary waste of disk space.

**Comment by barbudreadmon** [comment] 2022-10-03 11:08
Ok, so it seems the merge tag was only used when the rom name was matching between parent and clone, while it should actually always be used if i understand you correctly.
Then it should be fixed with https://github.com/finalburnneo/FBNeo/commit/4644b7453652efb317e1e578057b081095702297 .

**Comment by crashGG** [comment] 2022-10-03 12:23
Yes, this fix finally solved the problem

**Comment by barbudreadmon** [comment] 2022-10-03 16:46
I had to revert, it made a mess with bios for some reason (see https://github.com/libretro/FBNeo/commit/b675d5dd77b6852f7e7579e283127ce01c563635), i'll try to take another look soon.

**Comment by barbudreadmon** [comment] 2022-10-04 18:22
it *should* be fine with my latest commit

**Comment by barbudreadmon** [comment] 2022-10-05 07:24
I had to revert this again, it was still a mess due to parent/clones using different bioses (namco c69/c70, ...). I'll make one last attempt soon but i'm starting to wonder if it can actually be fixed.

**Comment by barbudreadmon** [comment] 2022-10-07 09:52
With https://github.com/finalburnneo/FBNeo/commit/786984ccce754fdd5b7cbaf79aff08b334616bd4, i think i've got a solution without regression.

I didn't find a solution for parent/clones using different bioses though, but the issue was already there and apparently not causing any actual problem. The most proper solution - if we really want to - might be to break parent/clone relation when bioses differ.

On that note i'm wondering if it's right for `emeraldah` to use `namco69` as bios, this hack looks based on the `namcoc70` version of this game.

**Comment by crashGG** [comment] 2022-10-07 20:24
<img width="314" alt="2022-10-07_232049" src="https://user-images.githubusercontent.com/80488411/194646798-9d9b2d56-f464-43fb-b2ad-c56002321c45.png">

Maybe could refer to the writing method of mame xml, it does not write the bios into the rom paragraph, but write into the device paragraph

**Comment by barbudreadmon** [comment] 2022-10-07 21:46
That device node has no meaning for dat managers.
Unlike us, MAME isn't considering those bioses as boardroms, and it has its own issues so that's not something we'd want to do.

**Comment by crashGG** [comment] 2022-10-09 02:53
> That device node has no meaning for dat managers. Unlike us, MAME isn't considering those bioses as boardroms, and it has its own issues so that's not something we'd want to do.

I mean,maybe could move the bios out of the boardroms in this driver, and exist as a separate device file,like mame. This also has the advantage of removing the repeated roms in each game. The size of the game sets can be reduced to a certain extent.

**Comment by barbudreadmon** [comment] 2022-10-09 06:41
>maybe could move the bios out of the boardroms in this driver, and exist as a separate device file,like mame

As i said, that's not something we'd want to do, not only that would require major changes to our framework but that would also forbid users from having non-merged romsets with bios included for those games.

**Comment by crashGG** [comment] 2022-10-09 07:18
Thank you for your efforts and contributions for fbn, the current fix has been quite good.

**Closed** 2022-10-09 07:26 UTC
