### ISSUE TITLE
Horizontal stretching for vertical orientation games

### ISSUE THREAD

**Issue by Panderner** [finalburnneo/FBNeo#114] opened 2019-09-26 16:05 UTC
There's a issue when you set a 1:1 PAR in aspect ratio on retroarch the vertical orientation games stretches to horizontal

**Comment by barbudreadmon** [comment] 2019-09-26 17:49
That's not a core, that's a frontend issue, duplicate of https://github.com/libretro/RetroArch/issues/8876. Closing.

**Closed by barbudreadmon** 2019-09-26 17:49 UTC
