### ISSUE TITLE
Street Fighter III New Generation VS Screen Corrupted Background

### ISSUE THREAD

**Issue by BilonFullHDemon** [finalburnneo/FBNeo#1439] opened 2023-04-14 11:55 UTC
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead
![sfiii-230413-180752](https://user-images.githubusercontent.com/130759532/232036686-eba49427-b100-40fd-836c-fbea4a458aa5.png)

**Comment by barbudreadmon** [comment] 2023-04-14 12:05
This is a known issue that was intendedly left out, because fixing it would be a major drop of performance for 1 single frame in 1 single cps3 game.

**Comment by BilonFullHDemon** [comment] 2023-04-14 12:08
Happens always after first fight on every next vs screen, some times more sometimes less noticeable but it there,
I found a note on old CPS3 standalone emu that fixed that and it might help understand what's wrong. "Fixed palette transformation for flashes, and fadeing/outs, now 
blacks properly fade to white"

**Comment by BilonFullHDemon** [comment] 2023-04-14 12:11
MAME current core somehow fixed it too and performs very good so maybe there is a way. Thank you

**Comment by barbudreadmon** [comment] 2023-04-14 12:12
As i said, this is a known issue.
We already know about the fix (missing dma implementation iirc), but the drawbacks were deemed too big to fix 1 single frame in 1 single cps3 game.

**Comment by barbudreadmon** [comment] 2023-04-14 12:26
>performs very good

MAME performs at around half our speed, despite the benefits of using a dynarec for its SH2 emulation. This 1 frame fix is incresing requirements severalfold.

**Comment by dinkc64** [comment] 2023-04-15 15:49
I might try to fix this after I get a chance :)

**Comment by dinkc64** [comment] 2023-04-16 05:50
barbudreadmon, we're actually emulating everything how it should be as far as the timers go for palette dma.  I found an issue somewhere else which limits the effective palette dma's per frame.  I managed to fix it, but, now I'm having trouble elsewhere.  Is there a chance you could meet up with me around 9am detroit time and help run a test or 2?

**Comment by barbudreadmon** [comment] 2023-04-16 08:26
>that thing about using more cpu is a non-issue now, that was actually overcome sometime in the past, and maybe I forgot to mention it. (unless I'm thinking about the wrong thing)

Oh ? If my memory serves me right, you talked about a full fix you made and ditched because it heavily screwed performance, and afterward you found a way to reduce the original issue which spanned over multiple frames to 1 single frame without any drawback.
It's very nice if you think it can now be fully fixed without any major drawbacks.

I can't meet today, maybe tomorrow ?

**Comment by dinkc64** [comment] 2023-04-16 13:17
Sounds good! :)

**Comment by dinkc64** [comment] 2023-04-17 13:55
@BilonFullHDemon the bug should be fixed now, please give it a try.  I'm not too good at fighting games, so I only did a quick test.

best regards,
- dink

**Closed** 2023-04-21 04:43 UTC
