### ISSUE TITLE
Storm Blade, black lines between tiles on stage 6

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#870] opened 2021-11-15 11:29 UTC
There's some black lines clearly visible in the snow on stage 6 in several spots.

![stmbladej-211115-113941](https://user-images.githubusercontent.com/6266038/141774027-3a7cc6e2-7a1e-428a-b89a-44b01e453aed.jpg)

I see it as well in many MAME videos, while on this pcb recording it's a lot more subtle:

https://youtu.be/AcGA3jgWXX4?t=550

I wonder if there's something that can be done about this?

**Comment by barbudreadmon** [comment] 2021-11-15 11:51
Thanks for the report !
Could you maybe add a savestate so that we can reproduce this more easily ?

**Comment by Tatsuya79** [comment] 2021-11-15 13:59
RetroArch state for Storm Blade (Japan):
[stmbladej.zip](https://github.com/finalburnneo/FBNeo/files/7539157/stmbladej.zip)

It starts from this point on, more visible when moving side-way.

**Comment by barbudreadmon** [comment] 2021-11-15 14:31
converted to standalone format : [stmbladej.zip](https://github.com/finalburnneo/FBNeo/files/7539310/stmbladej.zip)

**Comment by dinkc64** [comment] 2021-11-17 14:54
yikes, this one is tricky.  sprites are behind the tilemaps by a frame, changing the x/yoffset of the tmap/sprites causes worse issues so that's not an option.  Later today (when have more time) I'll try delaying the tilemaps by a frame..if it's easily possible w/o mutilating the code too much.

best regards,
- dink

**Comment by dinkc64** [comment] 2021-11-17 18:04
Tatsuya79,
Thanks for the bug report :)
I just found a really nice solution to the problem, it needs a bit more testing and cleaning up - gonna do that after a nice break.  Hopefully it'll make it in by tonight.

best regards,
- dink

**Comment by dinkc64** [comment] 2021-11-18 06:09
The fix is in! :)
The state format needs to change slightly for ssv due to the new code/variables.  I've kept it so you can finish your game with your current savestates.  After trying out the new code, please let me know when you've finished your game so I can update the state format.  The first frame after a state loads will look a little wrong until I make the change.

best regards,
- dink

**Comment by Tatsuya79** [comment] 2021-11-18 10:33
Nice, looks perfect now! 😃 

Side effect is 3 frames of reaction instead of 2 before though. This can be fixed with runahead but it's there.

**Comment by dinkc64** [comment] 2021-11-18 14:48
Great!
I believe the pcb has the same delay on sprites in order to render it properly.
This morning I managed to get it to respond on the second frame, or first frame for the other games in ssv.

best regards,
- dink

**Comment by dinkc64** [comment] 2021-11-18 15:18
After Barbudreadmon moves over the latest lag-fix, would you be interested in testing a few ssv games to make sure I didn't break anything?  My todo list is so insane right now, any help would be very appreciated.

**Comment by Tatsuya79** [comment] 2021-11-18 23:09
If you look at MAME for this game frame by frame, it's really emulated strangely with different parts of the ground refreshing at a different pace and even having gaps between them. Good chance it's wrong.

I went through the game in FBN on the latest 2 frames reaction changes, I noticed the explosion dark circle spot on the ground (like after you destroyed some tanks in stage 1) are not moving following the scrolling.
They go up and down almost every frame.

**Comment by dinkc64** [comment] 2021-11-19 06:28
Sure,  I wouldn't expect you to play/test the mj games :)

**Comment by dinkc64** [comment] 2021-11-19 06:41
Regarding the explosion spot, we have a choice:
1: synchronize the larger sprites to the tilemaps (such as land in stage 6) to the tilemaps, with a side effect of smaller sprites being off a frame
2: sync. the explosion spots to the tilemaps, (how it was before), and the larger sprites will become unsynched / lines will appear in st. 6

Arcade pcb's were never meant to be single frame stepped, but considering how most other games work with spritebuffering etc, It's most probable that the pcb is doing #2

**Comment by dinkc64** [comment] 2021-11-19 06:50
Here's pcb proofs:
https://youtu.be/lu6sd9uMk7A?t=385  @ 6:30 - very obvious (yellow tank exploded)
https://youtu.be/7Ts0OmPUWH4?t=521  @ 8:46

best regards,
- dink

**Comment by Tatsuya79** [comment] 2021-11-19 10:09
OK nice you found another footage where it's noticeable.  
I was checking the other one and couldn't see it happening. That's fine then. 👍 

That's hard to make sure about the scrolling smoothness at 30fps recording too...

**Comment by Tatsuya79** [comment] 2021-11-19 15:36
I played some other ssv games.

Change Air Blade is fine, except maybe a really fast garbage frame during a flashing effect, if you let the demo run until the point where they explain the different buttons and power up.

Drift Out '94 seems fine too, the big camera jumps when hitting a wall seem to be there on pcb too.
Again a game with some stutters that could be on the original machine but it's hard to tell.
(perhaps just because they move the camera asynchronously to the main scrolling, like in Storm blade when going sideways)

Dyna Gear was fine except a really loud explosion on a stage 2 monster.
RA savestate:
[dynagear.zip](https://github.com/finalburnneo/FBNeo/files/7571271/dynagear.zip)

**Comment by Tatsuya79** [comment] 2021-11-19 22:20
Survival Arts, right in the intro:

![survarts-211119-231208](https://user-images.githubusercontent.com/6266038/142698727-ba2b27d3-afef-41e3-94fc-546e1a8103bf.jpg)

**Comment by dinkc64** [comment] 2021-11-22 04:20
Tatsuya79,
Thank you for the info!  Over the past couple days I've been frantically trying to find a method that will work perfectly for every game - I think I'm pretty close to getting it.

best regards,
- dink

**Comment by dinkc64** [comment] 2021-11-22 06:15
Hi Tatsuya79,
I've committed my latest work on ssv, with a buffering method that preserves raster effects.
If you get a chance - please do a quick try of Storm Blade, TwinEagle 2, Ultra X W., and Survival Arts when the code has made it to libretro side & and let me know what you think.

p.s. I didn't forget about the ugly sound in dynagear st. 2, will definitely try to get to it soon
best regards,
- dink

**Comment by Tatsuya79** [comment] 2021-11-22 13:28
I went through Twin Eagle 2, it seems good now apart from some glitches on the last stage.
You can destroy the buildings with button 2 ground missiles and then the flames appearing look wrong.
(a bit like in this emu footage: https://www.youtube.com/watch?v=gkD9F-IDM6A )

RA savestate:
[twineag2.zip](https://github.com/finalburnneo/FBNeo/files/7581378/twineag2.zip)
 
Did a quick tests on other games and everything seem fine now, great work on all this! 😄

**Comment by dinkc64** [comment] 2021-11-22 14:14
@barbudreadmon can you please convert this state to regular fbneo for me? :)

**Comment by barbudreadmon** [comment] 2021-11-22 14:40
@dinkc64 sure, here it is : [twineag2.zip](https://github.com/finalburnneo/FBNeo/files/7581962/twineag2.zip)

**Comment by dinkc64** [comment] 2021-11-22 14:41
thanks!

**Comment by dinkc64** [comment] 2021-11-23 03:38
Tatsuya79,
This is good news! thanks for testing :)
Regarding the fire in the last level of Twin Eagle 2, I really think that the emulator is rendering it properly, basically a game-bug or oversight.  At such Dark levels on a real crt it probably looked just fine.

best regards,
- dink

**Comment by Tatsuya79** [comment] 2021-11-23 13:46
Or maybe a bad dump or copy protection. 🤷‍♂️ 
Can't find a pcb footage on this level.

**Comment by dinkc64** [comment] 2021-11-24 04:14
After doing some investigation:
x The same fire sprites are used in other levels and display just fine
x They are displayed in the wrong order / wrong flipping (as ordered by the game) in the last level
... if I swap the flipping bit so it displays fine on the last level, it breaks fire on all other levels, as well as most sprites are broken.
x If the program data was bad due to a bad dump, the startup checksum would fail.
Knowing this, I'd say it's a 99% bug in original code and 1% bug in cpu core or gfx rendering code (very unlikely, but not ruled-out)
... but we'll never know for sure unless someone does a pcb recording :)

best regards,
- dink

**Comment by dinkc64** [comment] 2021-11-24 04:15
Just fixed the clipping code used by twineag2, this gives the game a clear up / draw down-sort of animation for scene transitions.

**Comment by dinkc64** [comment] 2021-11-26 14:10
I think ssv is as good as it can possibly get now, if anything else comes up, re-open this.

best regards,
- dink

**Closed by dinkc64** 2021-11-26 14:10 UTC

**Comment by dinkc64** [comment] 2021-11-26 15:22
re: Dyna Gear
fixed the clipping that happens on the st.2 midboss.  Thanks again for all the issues you've found this time! :)

best regards,
- dink
