### ISSUE TITLE
Prehistoric Isle in 1930 and its clones - The 2nd controller when playing through Kaillera doesn't work at all

### ISSUE THREAD

**Issue by dangonzilla** [finalburnneo/FBNeo#1673] opened 2024-02-12 20:02 UTC
Hello,

When playing Prehistoric Isle in 1930 and its clones there is a Kaillera bug. The 2nd controller when playing through Kaillera doesn't work at all. Apparently the second player is also controlled by the first player in Kaillera.

Can you check it, please? 

Thank you!

**Comment by dinkc64** [comment] 2024-02-13 01:53
Hi dangonzilla,
thanks for the bug report!  The problem is fixed now :)

best regards,
- dink

**Comment by dinkc64** [comment] 2024-02-13 14:44
actually, I'm sorry, the fix didn't make it in yet - I'm having trouble with my git stuff, hopefully will be fixed soon and can sync. the code....

**Comment by dangonzilla** [comment] 2024-02-13 19:26
Hi Dink,

we have tested it with the latest FBNeo version and it works like a charm!

Thank you very much!

Best Regards,
Daniel.

**Closed** 2024-02-13 19:27 UTC
