### ISSUE TITLE
froggrs "Frogger" (Scramble hardware) Bootleg?

### ISSUE THREAD

**Issue by Redemp** [finalburnneo/FBNeo#380] opened 2020-06-21 13:51 UTC
The dat reports 
froggrs "Frogger" (Scramble hardware) 
But Mame says its a Bootleg 
[froggrs "Frogger" (Coin Music, bootleg on Scramble hardware](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=froggrs&arcade_only=0&autosearch=1)

FB neo 0.2.97.44 Built from source 06.21 Windows Gui

**Comment by barbudreadmon** [comment] 2020-06-21 14:54
Just to confirm because your msg on retropie's forum wasn't exactly cristal clear : the issue is about the game not appearing when the bootleg filter is applied, right ?

**Comment by Redemp** [comment] 2020-06-21 15:01
> 
> 
> Just to confirm because your msg on retropie's forum wasn't exactly cristal clear either : the issue is about the game not appearing when the bootleg filter is applied, right ?

Yes that is correct.

**Comment by barbudreadmon** [comment] 2020-06-21 15:47
should be fixed by https://github.com/finalburnneo/FBNeo/commit/bda3ee5176d19e3669d254c1e85ce10f39e0d969

**Closed** 2020-06-22 07:41 UTC
