### ISSUE TITLE
Super Chase (superchs) stutter graphics during steering.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#288] opened 2020-02-29 20:40 UTC
When you steer left/right during game the graphics of the road seems stutter.

In latest mame graphics is smooth during steer.

**Comment by dinkc64** [comment] 2020-02-29 23:47
I think this has to do with analog sensitivity, perhaps?  I get the exact same result with the latest mame and fb, so I could be looking at the wrong thing.  Could you please elaborate?
It seems like when I move really fast, the "camera angle" of the road moves fast, but if I move the analog joy slow, it moves smoothly.  I can see how fast I'm moving by watching the steering wheel move :)

**Comment by fastpop72** [comment] 2020-03-01 08:22
@dinkc64 I tried some analog settings but i can't run smooth the steering... Maybe Mame has more settings about analog emulation.

I made a little video for you to see the stuttering, i used digital controls for it:

https://youtu.be/rkO6kqe7w2Y

**Comment by dinkc64** [comment] 2020-03-01 14:04
oh, digital eh?  Is this with the libretro core?  If so, @barbudreadmon will need to check this one out.  I think it needs an input slider for digital -> analog to work right.  
On the other hand, if you use an analog stick (analog thumbstick on my ds3 gamepad) it is perfectly smooth in fbn and mame standalones.

**Comment by fastpop72** [comment] 2020-03-01 14:39
I tried also using my mouse in FBN standalone but with no luck. Mouse is not OK for driving games...

**Comment by dinkc64** [comment] 2020-03-01 16:52
I see what you mean by the mouse.  I will look deeper into it tonight - I think it needs some smoothing code! :)

**Comment by barbudreadmon** [comment] 2020-03-01 17:04
I don't see an easy way out of this : 
- retroarch doesn't emulate a "condenser" system when using dpad for analog controls
- retroarch won't tell if the analog inputs it provides comes from a real analog or an emulated analog, so i can't detect & switch to the slider thingy

Imho, that's a retroarch issue, it should implement a "condenser" system when remapping dpad to analog. The only other way to deal with this would be to add another control scheme where analogs are directly mapped to dpad & input slider are used, however : 
- we already have 6 control scheme, adding more seems very bad for user experience and code clarity
- seems like a workaround

**Comment by grant2258** [comment] 2020-03-01 18:07
Its easy to distinguish analog controls  in retroarch. Digital returns a 1 or 0 analog returns less than zero or bigger than 1. Mame 2003 manages this without issues on retroarch you will need code in the emulation core itself that maps the digital in steps when using analog controls though.

**Comment by barbudreadmon** [comment] 2020-03-01 19:00
> Digital returns a 1 or 0 analog returns less than zero or bigger than 1

Digital returns less than zero & bigger than 1 when remapping dpad to analog : it would be impossible to use dpad for analog otherwise.

> Mame 2003 manages this without issues

You are probably talking about remapping through mame osd, where dpad is always dpad, and analog is always analog, except if you mess with retroarch's remapping first, which is not recommended in mame cores afaik.

**Comment by grant2258** [comment] 2020-03-01 19:46
nope im not a digital control is a zero or one.

**Comment by grant2258** [comment] 2020-03-01 20:05
@dinkc64 does fbneo do an incremental counter when using analog. What i mean is if its say after burner and you press left do the logic keep the counter going up until analog max is reached if the key is kep pressed and digital control being used in analog?

**Comment by dinkc64** [comment] 2020-03-01 21:17
Tonight I am going to do a little experimenting with the game because even though it seems OK with my analog "thumbstick", it goes completely bonkers when using the mouse.  I think something is a little off :)

grant2258, it can do that although I haven't really explored the option too much.

**Comment by barbudreadmon** [comment] 2020-03-01 22:33
> Retroarch maps dpad to lstick and the original digital control it a dual input at the same time when you map the analog as digital in controls.

That part is true, however i'm talking about something completely different here : `input_cb(port, RETRO_DEVICE_ANALOG, RETRO_DEVICE_INDEX_ANALOG_LEFT, RETRO_DEVICE_ID_ANALOG_X);` will return values between -32768 & 32767, not 0/1, whatever the actual controls behind it. 

Are you suggesting to do both `input_cb(port, RETRO_DEVICE_ANALOG, RETRO_DEVICE_INDEX_ANALOG_LEFT, RETRO_DEVICE_ID_ANALOG_X);` & `input_cb(port, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_LEFT/RIGHT);` at the same time, and guess if it's "emulated analog" from that ? I guess that could work, however : 
- iirc there are a few fbneo games using left analog + dpad, they'll probably break from this
- it's very hacky, not sure what would be the less ugly way to do this, it's especially bad since i can't guess before the user press those controls, and i would have to re-evaluate internal mapping after that.

Imho, not a proper solution either, just another workaround, the frontend implementation is what's needed here.

**Comment by grant2258** [comment] 2020-03-01 23:53
Im looking at the sdl port in all honesty. From retroarch mame setup was different than what we have here it accepted digital inputs and converted them automatically if needed. If a real analog signal was found it would over ride any digital mapping through its logic. Im not suggesting you change anything in your port. 

Im having some issues with the sdl port and the retroarch port on the sdl port. I tried afterburner and I can only do a roll to the right its not working with the left roll on the sdl port. 

On retroarch i cant do a roll at all left or right tried a vx4 and xbox1 wireless controller. I think there is something needed in both ports as far as the analog handling goes. Ill need to trace the code though and see whats going on in the sdl port at least. 

Can you do a roll in afterburner?  Ill need to see the values dinput is giving for analog it might be a difference in value range(just a guess because when i working on mame it wanted a specific input range for analog so it had to be converted). 

In all honesty this is an analog control anyway and its not working correctly i think the mapping is another issue. Are you able to do rolls in afterburner on a properly mapped axis?

**Comment by dinkc64** [comment] 2020-03-02 03:45
grant2258, do a simple test with standalone and sdl port to see what's going on with the analog values:
edit drv/sega/sys16_run.cpp
find the XboardFrame() function
under this line: "System16MakeInputs();"
add: "bprintf(0, _T("System16AnalogPort0  %x\n"), System16AnalogPort0);"

in standalone load up afterburner and go full left and full right with the stick.  note the values
do the same with sdl port,
then, let me know what you get for each,

best regards,
- dink

**Comment by grant2258** [comment] 2020-03-02 04:11
full left is f810 center 9 right 7f0 ( with original code). I cant compile stand alone now sure what env i need to compile it.

**Comment by dinkc64** [comment] 2020-03-02 04:28
I compiled the debug code in standalone:
center: 0
left: 0xfc00  (-1024 decimal)
right: 0x3ff  (1023 decimal)
Now, if we can make the sdl port return this, we'll be set.

**Comment by dinkc64** [comment] 2020-03-02 04:29
do you think you could make a new bug for the sdl analog input issue?

**Comment by grant2258** [comment] 2020-03-02 04:33
yea dont want to spam here it Id like to try a few things first if thats ok during the week. Ill make the bug report after work.

**Comment by barbudreadmon** [comment] 2020-03-02 06:57
> On retroarch i cant do a roll at all left or right tried a vx4 and xbox1 wireless controller

I can do both, you probably have some setup or hardware issue.

> you need to scale your analog values to 65536 for libretro

The libretro frontend provides values between `-0x7fff` & `0x7fff`, in my port i convert them to `0`-`ffff` by casting into an UINT16 (i think standalone is doing exactly the same).

**Comment by grant2258** [comment] 2020-03-02 16:01
Not too fussed if its working for you thats fine. Mame2003-plus analog controls are working fine for me as well in retroarch not sure what the issue is there not to worry unless someone else experiences it. The controllers work fine in standalone and all configs where deleted. Ill just keep on looking into the sdl port.

**Comment by barbudreadmon** [comment] 2020-03-02 17:18
I can reproduce your issue if i set "Analog Speed" below 80% in core options, maybe you are reducing analog sensitivity through core options or the frontend setting that appeared a few RA releases ago ?

**Comment by dinkc64** [comment] 2020-03-02 17:31
grant2258, in the sdl port can you set the Left/Right axis to your analog stick instead of joyslider?
Then tell me the values for far left/right/center.  It will better help me figure out where the problem is coming from.

**Comment by grant2258** [comment] 2020-03-02 18:06
@dink64 

I did get it solved on the sdl port removing the >>1 here fixed it. 

https://github.com/finalburnneo/FBNeo/blob/ddae40dab24d593248fba7ddb699ce018d8b4445/src/intf/input/sdl/inp_sdl2.cpp#L466

its working via full axis and joy slider. Im going to add the rotary mapping games add a dead zone. 


@barbudreadmon the frontend is on 1.0 and the core is set to 50% the defaults ill try change it to 80. I can roll one way with it set at 80% so its an improvement but it acting like the sdl port was before for me.

**Comment by barbudreadmon** [comment] 2020-03-02 18:29
> the core is set to 50% the defaults

default is and has always been 100%, see https://github.com/libretro/FBNeo/blob/19458aa1346eec1556ba5f839d7943639c8d1868/src/burner/libretro/retro_common.cpp#L194-L202

**Comment by fastpop72** [comment] 2020-03-02 19:34
After @dinkc64 fixes, the stering is much less stuttering with digital controls, and with mouse there's a improvement, too.

**Comment by grant2258** [comment] 2020-03-03 15:29
@barbudreadmon i have no idea how that was set to 50 i usually leave settings in ra alone too time consuming to debug it and not back to defaults option.

**Comment by barbudreadmon** [comment] 2020-03-03 15:39
i have a theory : a few months ago i updated the core options code for core options "v2" support, maybe it messed up previously saved core options, it would also explain the recent surge of people having issues resolved by deleting their older fbneo core options.

**Comment by grant2258** [comment] 2020-03-04 18:12
You make a good point there could explain the problems users where experiencing might be a good idea to post advice to upload the options file to find where its causing issues and if it can be worked around.

**Closed** 2020-03-22 17:36 UTC
