### ISSUE TITLE
Red Gyruss

### ISSUE THREAD

**Issue by coyonut** [finalburnneo/FBNeo#1622] opened 2023-12-30 21:16 UTC
Hello. Gyruss and his clones are using the wrong palette with no blue colors. The game displays a red color tone.
Its me or its a bug?
![gyruss-12-30-215312](https://github.com/finalburnneo/FBNeo/assets/87364258/bb25c363-9816-4f21-8125-8a6112a2bf95)

**Comment by barbudreadmon** [comment] 2023-12-30 21:21
I can't reproduce this, maybe this is due to some sort of specific setting you are using ?

**Comment by dinkc64** [comment] 2023-12-30 22:50
Hi coyonut,
On my side, the colors are correct.  To help narrow down the cause of the problem,
Could you please tell some information?
Which fbneo are you using (stand-alone exe, or libretro)

If it's the stand-alone fbneo, please
zip and drag & drop these files to your message, from the fbneo directory:
config\games\gyruss.ini
config\fbneo.ini

best regards,
- dink

**Comment by coyonut** [comment] 2023-12-31 12:29
Tested with last debug build downloaded yesterday. But working ok with normal (no debug) version downloaded today.
[fbneo64.zip](https://github.com/finalburnneo/FBNeo/files/13801154/fbneo64.zip)
included config files of both versions

**Comment by dinkc64** [comment] 2023-12-31 14:24
Thanks for the info's & files, I tracked it down to the gamma setting under the Basic blitter, it's enabled with "hardware" mode, which unfortunately doesn't work on a lot of systems since - I think, WinXP or so. 

best regards,
- dink

**Comment by dinkc64** [comment] 2023-12-31 14:28
Actually, I'm wrong about the above message, while Gamma feature doesn't work well with newer systems, the red color actually is coming from a driver bug which only appeared when the Gamma option is used.  It's fixed now :)

best regards,
- dink

**Comment by dinkc64** [comment] 2024-01-01 05:40
coyonut,
I found a bunch of other games that had the same issue with Gamma enabled, then fixed them as well :)  Big thanks for helping find this bug!  Happy new year!

best regards,
- dink

**Comment by coyonut** [comment] 2024-01-01 16:35
Nice! Thanks dinkc64 for finding and fixing it. :)

Happy new year!

**Comment by dinkc64** [comment] 2024-01-06 06:23
Always welcome, thanks buddy!

best regards,
- dink

**Closed by dinkc64** 2024-01-06 06:23 UTC
