### ISSUE TITLE
dark edge pcb reference

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1508] opened 2023-07-02 20:19 UTC
hello
i find a gameplay of dark edge in pcb for reference
https://www.youtube.com/watch?v=riO1yb95z7s

**Comment by juan200213** [comment] 2023-07-04 01:09
hey respond my issue

**Comment by juan200213** [comment] 2023-07-04 01:09
whats happen

**Comment by barbudreadmon** [comment] 2023-07-04 06:44
closing as duplicate of https://github.com/finalburnneo/FBNeo/issues/1145

**Closed by barbudreadmon** 2023-07-04 06:44 UTC

**Comment by juan200213** [comment] 2023-07-04 14:12
But I have the PCB

**Comment by barbudreadmon** [comment] 2023-07-04 14:42
>But I have the PCB

I believe the answers you were given in the previous issue were clear enough.

**Comment by dinkc64** [comment] 2023-07-07 05:09
its fixed now
