### ISSUE TITLE
Alien 3 the gun elevator panel flickering

### ISSUE THREAD

**Issue by juan200213** [finalburnneo/FBNeo#1330] opened 2023-02-06 00:25 UTC
Hello
In the video game alien 3 the gun for Sega system 32 the panel of the elevator where do you select the floors in level 3 flickers so much
Please fix it 
Thanks
https://youtube.com/clip/UgkxpNrA_arF5K83TQJT_y6bZtuS8Cx6iFvi?si=EnSIkaIECMiOmarE

**Comment by juan200213** [comment] 2023-03-07 16:44
Hello, you have not answered me about elevator panel flickering please answer me thanks

**Comment by barbudreadmon** [comment] 2023-03-07 16:45
duplicate of https://github.com/finalburnneo/FBNeo/issues/1308 and many other issues

**Comment by dinkc64** [comment] 2023-03-09 14:23
I can't fix it, sorry!
It would be helpful to see how it works on a PCB (or arcade machine) but I can't find one.

best regards,
- dink

**Closed** 2023-09-27 15:59 UTC
Labels: bug, emulation, cantfix
