### ISSUE TITLE
Missing controls using a trackball and "Mouse (Ball only)" option.

### ISSUE THREAD

**Issue by fastpop72** [finalburnneo/FBNeo#89] opened 2019-08-02 20:48 UTC
I added a trackball to the commands, i selected the "Mouse (Ball only)" on the Controls menù and everything seems works well with lightgun games.
I have instead an issue in Thunder Blade and Thunder Ceptor because when i select "Mouse (Ball only)" i can't accelerate because the core doesn't let me set the Accelerate or Throttle commands. I can only move (with trackball) and shoot (with buttons).

**Comment by dinkc64** [comment] 2019-08-02 23:06
@barbudreadmon, any idea?  :)

**Comment by barbudreadmon** [comment] 2019-08-04 11:51
> because the core doesn't let me set the Accelerate or Throttle commands

Actually, RetroArch is the one preventing that, it doesn't allow remapping for "hybrid" devices, a workaround would be what i explain in https://github.com/libretro/FBNeo/issues/71, i.e setting the buttons part to RA's device 1 which would need to be set as RetroPad, and the mouse part to RA's device 2 which would need to be set as Mouse. However that would need a major rewrite of the input code in my port, for a result which is totally unsatisfying for me.
Anyway, closing, better "hybrid" devices support is a duplicate of the issue i mention above. Also, i would appreciate if you opened your issues with the libretro port, especially frontend issues which are totally unrelated to upstream, in the repo dedicated to the libretro port : https://github.com/libretro/FBNeo/issues.

**Closed by barbudreadmon** 2019-08-04 11:51 UTC

**Comment by barbudreadmon** [comment] 2019-08-04 13:14
Not an ideal solution but i found a workaround, it will be available on the libretro buildbot in a few hours.

**Comment by fastpop72** [comment] 2019-08-04 13:36
@barbudreadmon Fantastic!!! Can't wait to try it!!! Thanks!

**Comment by fastpop72** [comment] 2019-08-04 15:25
Just tested, now Thunder Blade is OK, i can set the Throttle+/- to accelerate and  move with the trackball.
Nothing's changed in Thunder Ceptor instead, when i select "Mouse (Ball)" i can't set the Accelerate button.

**Comment by dinkc64** [comment] 2019-08-04 23:28
I made a mistake with thunder ceptor!
sorry! will check in code to fix accel. button, its accidentally mapped to p1 x-axis.

**Comment by barbudreadmon** [comment] 2019-08-05 05:53
Thanks, i intended to ask you on irc if it was ok to change those inputs :)

**Comment by fastpop72** [comment] 2019-08-05 07:45
Thunder Ceptor works now! Thanks!
