### ISSUE TITLE
Chase Bombers, runahead issue

### ISSUE THREAD

**Issue by Tatsuya79** [finalburnneo/FBNeo#872] opened 2021-11-15 15:58 UTC
Another one with runahead issues in RA 2nd instance mode: the landscape background disappears, it turns all black.

Also the colors in this game look really strange, like overbright/really low gamma. Same look in MAME.

Default:
![cbombersj-211115-164116](https://user-images.githubusercontent.com/6266038/141812255-30c2cdcc-e46e-4fe0-8be2-779684097e62.jpg)

Luminance down to 40%, contrast up to 450%:
![cbombersj-211115-164140](https://user-images.githubusercontent.com/6266038/141812343-76089b5c-ea7b-44e1-9d8f-7540fd57f80a.jpg)

You can see in that picture there's also a problem where the road get cut along a line (near the car wheels).
Looks a bit like tearing but it's not that. Happens in MAME too.

Can't find any real pcb footage...

**Comment by barbudreadmon** [comment] 2021-11-15 16:22
>Also the colors in this game look really strange, like overbright/really low gamma. Same look in MAME.

Probably related to this comment : https://github.com/mamedev/mame/blob/master/src/mame/drivers/undrfire.cpp#L66

**Comment by dinkc64** [comment] 2021-11-16 01:39
Can you please post a pic of the background disappearing?  It doesn't happen on my side, so I'll need to take cues from the picture.

best regards,
- dink

**Comment by barbudreadmon** [comment] 2021-11-16 10:16
I could only reproduce this by toggling 2nd instance runahead at runtime (after the race start) : 

![cbombersj-211116-111258](https://user-images.githubusercontent.com/10391265/141966357-ced484aa-74b2-4161-8457-5b8f6ed10790.png)

**Comment by dinkc64** [comment] 2021-11-18 15:14
Experimenting with some code to manipulate the palette, I got Chase Bombers to look great (as you did), but, Under Fire still looks like crap with it.  Perhaps I'll just enable it for Chase Bombers.

**Comment by dinkc64** [comment] 2021-11-19 14:47
Tatsuya79, I put in the contrast, luma changes you mentioned, havn't had a chance to figure out the other 2 issues though.

best regards,
- dink

**Comment by barbudreadmon** [comment] 2023-03-07 17:21
Closing as i think the issues have all been solved

**Closed by barbudreadmon** 2023-03-07 17:21 UTC
