### ISSUE TITLE
super model and fantasia bug

### ISSUE THREAD

**Issue by kounabi22** [finalburnneo/FBNeo#1883] opened 2024-09-23 12:52 UTC
Super Model (supmodel) start with wrong orientation and i have to enable vertical orientation.
Fantasia (Fantasia) you get to see the start screen and then a black screen with only the insert coin to see in bottom and you cant play, the clone fantasian works.

**Comment by barbudreadmon** [comment] 2024-09-23 13:12
I pushed a fix for supmodel. 
I think the other one is about rom loading, it also affects fantasiaa and fantasiab. I don't have time to look more deeply into it right now but maybe later.

**Comment by dinkc64** [comment] 2024-09-26 05:09
fantasia should be fixed now, too.  You'll have to forgive me, I didn't do any testing other than starting a game.  If you find any problems please let us know :)

best regards,
- dink

**Comment by kounabi22** [comment] 2024-09-26 13:32
for fantasia when you instert coin ,the text press 1 or 2 button dont apear compare to the clone fantasian ,
other than that i did not notice some other bug.
super model is ok.

**Comment by barbudreadmon** [comment] 2024-09-26 13:36
It doesn't appear either in MAME, so it might be how this game looks.

**Closed** 2024-09-26 13:45 UTC

**Comment by kounabi22** [comment] 2024-09-26 18:31
shall i open in again?

**Comment by barbudreadmon** [comment] 2024-09-26 18:36
The missing "press 1 or 2 button" is not a bug, so except if there is still another issue we missed, no you aren't supposed to re-open this.
