### ISSUE TITLE
Could you bring support for chd?  All my Neo CD roms are in CHD

### ISSUE THREAD

**Issue by carlosgamer23** [finalburnneo/FBNeo#1567] opened 2023-09-22 00:41 UTC
Could you bring support for chd?  All my Neo Geo CD roms are in CHD, It would be a great help if they supported .7z roms like MAME does too.  Congratulations for your work!

**Comment by barbudreadmon** [comment] 2023-09-22 05:42
7z is already supported.

You can convert your chd back to raw image using chdman.

Closing as a duplicate of https://github.com/finalburnneo/FBNeo/issues/79

**Closed by barbudreadmon** 2023-09-22 05:42 UTC

**Comment by carlosgamer23** [comment] 2023-09-29 12:52
> 7z já é suportado.
> 
> Você pode converter seu chd de volta para imagem bruta usando chdman.
> 
> Fechando como uma duplicata de #79

Technically, all current ROM sites put everything in CHD, that would be a lot of work... Apart from the space it would take up, would that cause any copyright issues for you?  I have never seen anyone or any company complaining about the use of Chd 🤔

**Comment by barbudreadmon** [comment] 2023-09-29 13:01
To repeat what was already answered to you on forum : libflac (which is necessary for reading audio from CHDs) contains components under GPL license, which is incompatible with a non-commercial license like ours.
