### ISSUE TITLE
Super Street Fighter II X: Grand Master Challenge (Japan) graphics continue issue

### ISSUE THREAD

**Issue by jmodlin37** [finalburnneo/FBNeo#1655] opened 2024-01-30 04:40 UTC
Super Street Fighter II X: Grand Master Challenge (940311 Japan)  >> ssf2xj

Guile, Boxer, Sagat, Ryu, Zangief, Dhalsim, Dee Jay, and Fei Long's hands are sticking out of the character frame in their continue screens. 

![ssf2xj-01-29-231843](https://github.com/finalburnneo/FBNeo/assets/158124601/244366d0-6664-4dec-b185-b027dcd70b27)
![ssf2xj-01-29-231910](https://github.com/finalburnneo/FBNeo/assets/158124601/78e516f6-911d-43ac-a723-5395bcf7d07b)
![ssf2xj-01-29-231924](https://github.com/finalburnneo/FBNeo/assets/158124601/178aed07-6111-4346-bcf4-45a145721c16)
![ssf2xj-01-29-231939](https://github.com/finalburnneo/FBNeo/assets/158124601/a32d936b-56d4-4a0d-b833-213d24e7acae)
![ssf2xj-01-29-232005](https://github.com/finalburnneo/FBNeo/assets/158124601/611c5233-4c2a-4ea8-8d71-767f2a8f489b)
![ssf2xj-01-29-232036](https://github.com/finalburnneo/FBNeo/assets/158124601/98729bc2-425d-45a9-8e6e-5963d1539276)
![ssf2xj-01-29-232053](https://github.com/finalburnneo/FBNeo/assets/158124601/916872fa-91c8-4274-b338-71329b1dc5b7)
![ssf2xj-01-29-232108](https://github.com/finalburnneo/FBNeo/assets/158124601/b02319fb-08b2-46f2-bf83-3d90ce3df815)

[ssf2xj savestates.zip](https://github.com/finalburnneo/FBNeo/files/14092821/ssf2xj.savestates.zip)

**Comment by barbudreadmon** [comment] 2024-01-30 08:51
Closing as duplicate of https://github.com/finalburnneo/FBNeo/issues/912
We'll consider reopening if you post footage of real **japan** pcb.

**Closed by barbudreadmon** 2024-01-30 08:51 UTC

**Comment by jmodlin38** [comment] 2024-01-31 02:29
I have footage for 8 characters which are Ryu, Guile, Fei Long, Boxer, Sagat, Zangief, Dhalsim, and Dee Jay's hands sticking in the character frame in their continue screens for Super Street Fighter II X Japan for MAME matching with Japan PCB.

https://github.com/finalburnneo/FBNeo/assets/158239782/3bfd74a2-f4a2-44a4-ae13-98876d613096


https://github.com/finalburnneo/FBNeo/assets/158239782/0d53cbb3-d62a-44cb-a036-a96105306211


https://github.com/finalburnneo/FBNeo/assets/158239782/d9778d8b-076e-449e-8851-6f13fe1d2885


https://github.com/finalburnneo/FBNeo/assets/158239782/af92cdbc-7654-474d-aed5-a9ba40fde052


https://github.com/finalburnneo/FBNeo/assets/158239782/e350c490-1054-4cb4-9f80-93f4a0e274c2


https://github.com/finalburnneo/FBNeo/assets/158239782/f03aaee2-9561-4d88-a2d8-0fd507b51226


https://github.com/finalburnneo/FBNeo/assets/158239782/a6011652-7146-4c70-92fe-3ea35226d0d2


https://github.com/finalburnneo/FBNeo/assets/158239782/728e1f1f-7efb-44ac-a656-d983bd6ad7cd

**Comment by jmodlin38** [comment] 2024-01-31 03:02
I have footage for 8 characters which are Ryu, Guile, Fei Long, Boxer, Sagat, Zangief, Dhalsim, and Dee Jay's hands sticking in the character frame in their continue screens for Super Street Fighter II X: Grand Master Challenge Japan for MAME matching with Japan PCB.

https://github.com/finalburnneo/FBNeo/assets/158239782/986fda92-4e8a-412d-a5ac-2b6bf310645b


https://github.com/finalburnneo/FBNeo/assets/158239782/f148f593-fd30-406f-9ccd-af8c4d3111d1


https://github.com/finalburnneo/FBNeo/assets/158239782/fd6d2521-5ca2-44a4-8a9b-8fe2b28db7d1


https://github.com/finalburnneo/FBNeo/assets/158239782/82b7bf69-0dca-4aed-9733-af0dc2c6a218


https://github.com/finalburnneo/FBNeo/assets/158239782/55004d7e-0794-4ae0-a4ea-e19116016207


https://github.com/finalburnneo/FBNeo/assets/158239782/b7339cd4-59dc-4cbb-bebe-5cdc057d2a83


https://github.com/finalburnneo/FBNeo/assets/158239782/a9491089-bdc4-4ec7-b8a6-6b097eb07497


https://github.com/finalburnneo/FBNeo/assets/158239782/75c57888-9894-461e-89b9-4a6514d17f38

**Comment by jmodlin38** [comment] 2024-01-31 03:03
I have footage for 8 characters which are Ryu, Guile, Fei Long, Boxer, Sagat, Zangief, Dhalsim, and Dee Jay's hands sticking in the character frame in their continue screens for Super Street Fighter II X: Grand Master Challenge Japan for MAME matching with Japan PCB.

https://github.com/finalburnneo/FBNeo/assets/158239782/f554c2f9-1c3e-4092-bfe3-b83907cd7927


https://github.com/finalburnneo/FBNeo/assets/158239782/d91fdf9f-6783-4cbc-8a15-fa7792db3be6



https://github.com/finalburnneo/FBNeo/assets/158239782/b72a9d9b-3fb5-444e-bb07-85201e0300dd



https://github.com/finalburnneo/FBNeo/assets/158239782/a23ec878-6880-49aa-af3c-f39fa75f8cb6


https://github.com/finalburnneo/FBNeo/assets/158239782/f8c6f506-6864-4a38-af23-34d1da96c88f



https://github.com/finalburnneo/FBNeo/assets/158239782/c17b19dc-69ca-45d0-97f0-e5dbc89580ba


https://github.com/finalburnneo/FBNeo/assets/158239782/95845bea-7660-41b3-9f9c-2694d1ac82e5


https://github.com/finalburnneo/FBNeo/assets/158239782/249f3cdd-fd4e-4be7-a70c-80781e1aa059

**Comment by barbudreadmon** [comment] 2024-01-31 07:54
>for MAME matching with Japan PCB

Since you refuse to understand, i'll deal with all your future posts accordingly.
