### ISSUE TITLE
the shocktro and neobombe roms do not work, there is an error when running them

### ISSUE THREAD

**Issue by EddyStalin** [finalburnneo/FBNeo#1585] opened 2023-10-22 19:21 UTC
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

**Comment by EddyStalin** [comment] 2023-10-22 19:22
the shocktro and neobombe roms do not work, there is an error when running them

**Comment by barbudreadmon** [comment] 2023-10-22 19:24
No, there is no error, they are working properly.
Please provide more informations or i'll have to close.

**Comment by dinkc64** [comment] 2023-10-23 00:18
EddyStalin,
Get the neogeo.zip bios rom and put it in your roms directory

best regards,
- dink

**Comment by EddyStalin** [comment] 2023-10-23 02:15
![shocktro-231022-211427](https://github.com/finalburnneo/FBNeo/assets/104610282/04098669-3f85-4e95-975b-96d8084cda48)

**Comment by barbudreadmon** [comment] 2023-10-23 05:44
This message is literally telling you that this is not a bug and that you should read the related libretro documentations (https://docs.libretro.com/guides/arcade-getting-started/ and https://docs.libretro.com/library/fbneo/), so that's what you should do instead of being here.

Your `shocktro.zip` and `neobombe.zip` romsets are wrong, and before you ask, we can't help you with acquiring the correct versions, this is something you'll have to figure out by yourself.

Closing.

**Closed by barbudreadmon** 2023-10-23 05:44 UTC
