### ISSUE TITLE
Gun games with analog control weren't right

### ISSUE THREAD

**Issue by JPman1aco** [finalburnneo/FBNeo#1758] opened 2024-04-19 12:17 UTC
When trying to use an analogue arcade gun that I converted to a PC controller with an Arduino.

I noticed that on the FBneo the aiming reticle doesn't follow the position of the gun, it just goes in the direction I turn the gun but doesn't return with the gun to the center.

Other analog games like After Burner II worked as expected with my gun and I was able to use it like an airplane control stick.

The FBneo improvement that made gun games more playable with mouse and d-pad broke support for the analog gun controller.

![gun](https://github.com/finalburnneo/FBNeo/assets/167532716/550dfbf3-8fda-4da1-aabc-2329be1a97bb)

**Comment by barbudreadmon** [comment] 2024-04-19 12:27
Basically the problem is that we don't use axis returned values "directly" for gun games, so when a stick is held right/left/up/down, the cursor keeps moving in that direction instead of staying at the position the stick is being held.
I don't know if there is a setting in win32 builds to handle this.

**Comment by dinkc64** [comment] 2024-04-21 00:38
@JPman1aco Hi, neat project!  Are you using the Windows version of FBNeo?

@barbudreadmon,  so basically: lightgun games on the lr port can be configured to use direct axis or go through burn_gun for gamepad/mouse use?  Is that what we need to do on the windows ui side?

**Comment by barbudreadmon** [comment] 2024-04-21 05:10
Yes he is using the win32 builds (i talked with him on discord before he posted this issue, took me a while to understand his problem).

FWIW, i pushed this change yesterday to the lr port : https://github.com/libretro/FBNeo/commit/c821b1008e31d40b6d0464f67a3bc0b1a3da4cce
So basically, if arcade gun is selected as an input device, i poll the stick, convert it into a width/height position, and send it to the game through `BurnGunSetCoords`, this is also what i do for lightgun devices (sinden, ...) except the polled "libretro input device" is different. This is what suited best the lr port since it was already using this function for lightguns, not entirely sure about the win32 builds.

**Comment by dinkc64** [comment] 2024-04-21 13:29
So basically for positional mode, we scale the input (0 (left/up) - 0x80 (center) - 0xff (right/down)) to the game's window size and feed that into BurnGunSetCoords()?

**Comment by dinkc64** [comment] 2024-04-21 13:55
@JPman1aco 
Hi,
Experimental Positional Mode has been added:
edit your config/fbneo.ini file and find this: bBurnGunPositionalMode, and set it to 1
load fbneo and try a lightgun game, I tested with Lethal Enforcers and it appeared to work fine.

Please let me know how it goes!

@barbudreadmon, maybe you can use this to simplify things on your end?

best regards,
- dink

**Comment by barbudreadmon** [comment] 2024-04-21 16:03
I'll give it a try :)

**Comment by dinkc64** [comment] 2024-04-22 00:19
barbudreadmon, I realized this might not be good for your use, we'd have to expand it to a per-device thing, which is no problem :)

**Comment by dinkc64** [comment] 2024-04-22 04:42
...you know, for example, if player 1 has a sinden or what OP has, and player 2 has a mouse or joy?

**Comment by barbudreadmon** [comment] 2024-04-22 05:38
Oh, you are right, it'd be a problem if players can't use different kinds of controller.
I might as well stay with my current implementation then, "don't fix what is not broken" as they say.

**Comment by JPman1aco** [comment] 2024-04-23 15:09
> @JPman1aco Hi, Experimental Positional Mode has been added: edit your config/fbneo.ini file and find this: bBurnGunPositionalMode, and set it to 1 load fbneo and try a lightgun game, I tested with Lethal Enforcers and it appeared to work fine.
> 
> Please let me know how it goes!
> 
> @barbudreadmon, maybe you can use this to simplify things on your end?
> 
> best regards,
> 
> * dink


Worked perfectly.

Playing with a gun controller is an experience that we no longer find on the streets.

**Comment by AngeloScipione** [comment] 2024-09-22 12:36
This work in Retroarch? I use a Xbox 360 joypad and "Analog Arcade Gun" and it doesn't work. However, in another core (flycast, as controller in Naomi's lightgun) is working. My objective is use Dolphin bar in mode 3 (controller) because IR sensor is used as a stick. It's perfect to play two players and only one bar.

**Comment by barbudreadmon** [comment] 2024-09-22 13:37
Yes it does work, and i don't understand anything at all about what you are saying. Your "report" couldn't be more confusing. xbox360 joypad + dolphin bar ??? IR sensor as a stick ?????? You didn't even mention the game you tried this on... 

Please open a proper issue, i'll close this one as it does work perfectly.

**Closed by barbudreadmon** 2024-09-22 13:37 UTC
