### ISSUE TITLE
Libretro and DIP Switch on NEOGEO games and internal neogeo setting menù.

### ISSUE THREAD

**Issue by DjDiabolik** [finalburnneo/FBNeo#1803] opened 2024-06-14 16:28 UTC
On my personal Arcade collection (My OS it's Ubuntu 22.04.4 LTS running current retropie setup script whit all update completed 5 minutes ago) i have some NEOGEO games.

For example:
Grand Prix Jokey (both set)
and many other

Pick Grand Prix Jokey... it's a betting games horse. In retroarch i can set some dipswitch but we know every neogeo games as also the built-in menù accessing by service menù (by default press "START" buttons for x seconds).
apparently it seems that what I set within this menu is ignored but it's respect the setting in the dip switch on retroarch.
On Grand Prix Jokey i can set....1 Coin = 9 credits but this setting it's on service menù and not in the dip switch on retroarch.
I hope I've given you an idea of ​​what I mean....

**Comment by barbudreadmon** [comment] 2024-06-14 16:52
Is that a question ?

>apparently it seems that what I set within this menu is ignored but it's respect the setting in the dip switch on retroarch

Yes, whatever is set in the eeprom will be overriden by the settings. 
A wild guess would be that it was done like this because the non-mvs bioses don't save eeproms.

**Comment by DjDiabolik** [comment] 2024-06-16 22:10
> Is that a question ?
> 
> > apparently it seems that what I set within this menu is ignored but it's respect the setting in the dip switch on retroarch
> 
> Yes, whatever is saved in the eeprom will be overriden by the settings. A wild guess would be that it was done like this because the non-mvs bioses don't save eeproms.

mmmmmmmmm....i have tryed to choose different neo geos bios for "Grand Prix Jokey" but there seems to be some problem for this specific games.
It directly appears that the game does not have its own configuration menu or it is not displayed correctly:
![immagine](https://github.com/finalburnneo/FBNeo/assets/9040397/1970e847-917b-465a-91f6-b752b8e6c4fc)

this is what I set in the neogeo bios menu.......... for every coin in theory it's will add five credit.... but look here:
![immagine](https://github.com/finalburnneo/FBNeo/assets/9040397/0ad739c7-5310-4882-bebb-a5ca749f78d5)
Apparently this games it doesn't have its own real service menu or the latter does not work correctly....

However, the configuration made in the neogeo bios menu seems not to be respected in the game.

**Comment by barbudreadmon** [comment] 2024-06-16 22:14
As i said, this is normal behavior. Eeprom is ignored in favor of settings.

I'll be closing soon if you have no other questions.

**Comment by DjDiabolik** [comment] 2024-06-16 22:23
> As i said, this is the intended behavior. Eeprom is ignored in favor of settings.

ah ok.... so this setting can be added in the retroarch menu (like a dipswitch) instead of in the bios service menu specifically for this game?

**Comment by barbudreadmon** [comment] 2024-06-16 22:47
Ok, i'm getting confused and i'm not sure anymore i understand what your report is about.
Could you please explain properly, with a step-by-step guide on how to reproduce your problem ?

**Comment by barbudreadmon** [comment] 2024-06-17 11:37
Ok, i was confused because you talked about "core options dipswitches" overriding "built-in dipswitches" in "many games", which would be the intended behavior whenever such dipswitches overlap. That's not what's happening here though since there is no overlap (no credit dipswitch in core options).

As for why this game doesn't respect the "built-in credit dipswitch", the behavior is exactly the same in MAME so it's probably not a bug. If i had to guess, i'd say it's just normal behavior due to this game being a gambling game.

I'll be closing soon except if i'm still misunderstanding your issue ?

**Comment by DjDiabolik** [comment] 2024-06-20 05:48
@barbudreadmon yes... i saw the same game on MAME it works exactly the same way.
![immagine](https://github.com/finalburnneo/FBNeo/assets/9040397/58689b5f-5024-4748-a03b-15ce5177152a)
At this point I think that's how it works and it's a shame :(

I thinks this games simply not respect the "SOFT DIP" on internal neogeo.... you can see if i have set 1 coin = 5 credit. But the games simply not respect this value. I think it's intentional. I honestly don't remember if the original arcade cabinet had a coin acceptor or did it have a banknote reader ?

**Comment by barbudreadmon** [comment] 2024-06-20 08:51
I don't remember seeing those mvs gambling machines in the flesh, so i wouldn't be able to tell. A search on google seems to say it was simply using an additional coin-hopper for payout.
Either way, i think it only makes sense that a gambling machine wouldn't give a crazy amount of tries for a single coin.

**Comment by DjDiabolik** [comment] 2024-06-20 15:53
Confirm.... One single coin.. one single credit :)

**Comment by barbudreadmon** [comment] 2024-06-21 08:21
I'll close

**Closed by barbudreadmon** 2024-06-21 08:21 UTC
