### ISSUE TITLE
Mouse movement - Bug?

### ISSUE THREAD

**Issue by SilentMRG** [finalburnneo/FBNeo#1359] opened 2023-02-27 20:10 UTC
Hello players,

I saw that there is possibility to map mouse movement. After remapping, in-game mouse movement does not work. All other commands work except mouse movement. Problem with my mouse is not because I use it in other games without problems. So I'm thinking maybe it's an emulator bug, or am I missing something?

The game I tried to play is Truxton II.

Thanks in advance!

**Comment by barbudreadmon** [comment] 2023-02-28 07:26
Mouse movements will work with games that originally used similar kind of devices (trackballs, spinners, lightgun). 

As i told you last time, i don't know how it would work with games expecting joysticks, like every arcade shmups including truxton 2. It's not a bug.

**Comment by SilentMRG** [comment] 2023-02-28 14:42
Thank you for the information! I think with ship shooters mouse movement would work. If this is implemented, it will be the differential for the emulator.

**Comment by dinkc64** [comment] 2023-02-28 14:54
SilentMRG, this is actually supposed to work, but it doesn't.  I'll try to figure it out shortly!

best regards,
- dink

**Comment by dinkc64** [comment] 2023-02-28 15:14
It's fixed now, please give it a try, updated exe's can be found here:
https://github.com/finalburnneo/FBNeo/releases/tag/latest
(if files aren't available, check back in a few minutes - the system might be in the process of generating anew)

best regards,
- dink

**Comment by SilentMRG** [comment] 2023-02-28 16:43
> It's fixed now, please give it a try, updated exe's can be found here: https://github.com/finalburnneo/FBNeo/releases/tag/latest (if files aren't available, check back in a few minutes - the system might be in the process of generating anew)
> 
> best regards,
> 
> * dink

Thanks so much for this quick fix! As soon as I get home from work I'll try it out.

Just one question: Do I need to re-download all the games, or will the ROMset I have not be affected?

Cheers!

**Comment by barbudreadmon** [comment] 2023-02-28 17:22
That fix doesn't affect romset versions, however if you are switching from a somehow old version of FBNeo to the latest, some of your romsets might require an update.

**Comment by SilentMRG** [comment] 2023-02-28 22:18
@dinkc64 Worked perfectly! The only thing I've noticed is that the stick sensitivity slider (I think it's gamepad related?) doesn't seem to work with the mouse. Having the option to adjust the mouse sensitivity would be very nice.

Thanks again for this amazing solution!

**Comment by dinkc64** [comment] 2023-02-28 23:01
Glad it works :)

That slider is for analog inputs, such as trackball, spinner, pedal/wheel/dial, & etc.
When mapping analog to digital, it just translates a movement - for example, moving the mouse up presses joystick up.  Sensitivity wouldn't apply here, because you can't press a joystick button more or less like analog - it's either on or off.

**Comment by SilentMRG** [comment] 2023-02-28 23:28
> Glad it works :)
> 
> That slider is for analog inputs, such as trackball, spinner, pedal/wheel/dial, & etc. When mapping analog to digital, it just translates a movement - for example, moving the mouse up presses joystick up. Sensitivity wouldn't apply here, because you can't press a joystick button more or less like analog - it's either on or off.

I understood. =) Anyway, a separate section for mapping the mouse movement "emulating" an analog stick with a slider to adjust the sensitivity... Would be really nice! Just a suggestion. ^^

Thanks for the good work on the mouse movement fix! It made my spaceship games more enjoyable. =D

**Comment by dinkc64** [comment] 2023-03-01 01:23
Glad to help! :)
best regards,
- dink

**Closed** 2023-03-01 01:23 UTC

**Comment by SilentMRG** [comment] 2023-11-08 20:10
Hey my man, how are you? I know the post is from 1000 years ago, but could you consider adding a bar to the project to adjust the Mouse sensitivity? As it is, it's playable, but it's hard as a rock compared to other games that have adequate mouse support, like Tyrian 2000 and Raptor Call of the Shadows. Yes, I already said something similar in another post, but I think that appropriate Mouse movement and Ship games combine with each other, and there is no Gamepad in this world that surpasses the glorious movement of the Mouse! Come on, man, make it happen for this poor old player. XD

**Comment by dinkc64** [comment] 2023-11-10 01:33
Hi SilentMRG,
I wish something like that were possible, but, its a difficult situation with no easy way to work around it.
All we can do is translate the mouse movement to a digital up/down/left/right, in doing so - you lose the things that are nice about an (pseudo)analog input like the mouse, such as velocity.  Of course, I would do it if it were possible.
Unfortunately the only thing I can do is suggest to get the power-ups that makes your ship move faster.

best regards,
- dink
