### ISSUE TITLE
skykid, skykiddx issues

### ISSUE THREAD

**Issue by arnoldsecret** [finalburnneo/FBNeo#112] opened 2019-09-20 06:52 UTC
`skykid` - erratic inputs from kbd causes game to reset and flip.

`skykiddx` - graphics screw-up, same issues as skykid despite different hardware.

**Comment by dinkc64** [comment] 2019-09-23 01:55
thanks! I fixed skykid.  skykiddx will come later as the issue is much harder to track down.

**Comment by dinkc64** [comment] 2019-10-11 04:03
skykid dx is fixed now, thanks for the reports! :)

**Closed** 2019-10-11 04:41 UTC
